Class {
	#name : #GASSTeacherTest,
	#superclass : #TestCase,
	#category : #'SmallSuiteGenerator-Tests-Generated'
}

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test1 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'giM|.cP'.
_var1 := 13199.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 13199 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 13199 .
self assert: _var0 equals: 'giM|.cP' .
self assert: _var1 equals: 13199 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_giM|.cP' .
self assert: _var6 equals: 13199 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test10 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'neAXiM|.cF'.
_var1 := 57.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var2 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 57 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 57 .
self assert: _var0 equals: 'neAXiM|.cF' .
self assert: _var1 equals: 57 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_neAXiM|.cF' .
self assert: _var6 equals: 57 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test11 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'c.c_'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: 'c.c_' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_c.c_' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test12 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '{.cH'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var2 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: '{.cH' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_{.cH' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test13 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'giM|.cP'.
_var1 := 150.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 150 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 150 .
self assert: _var0 equals: 'giM|.cP' .
self assert: _var1 equals: 150 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_giM|.cP' .
self assert: _var6 equals: 150 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test14 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'gR4iM|.c~'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: 'gR4iM|.c~' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_gR4iM|.c~' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test15 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'giM|.cP'.
_var1 := 150.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 150 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 150 .
self assert: _var0 equals: 'giM|.cP' .
self assert: _var1 equals: 150 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_giM|.cP' .
self assert: _var6 equals: 150 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test16 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'uKeAXiM|.c9'.
_var1 := 0.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 0 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 0 .
self assert: _var0 equals: 'uKeAXiM|.c9' .
self assert: _var1 equals: 0 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_uKeAXiM|.c9' .
self assert: _var6 equals: 0 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test17 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'uKeAXiM|.c9'.
_var1 := 0.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 0 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 0 .
self assert: _var0 equals: 'uKeAXiM|.c9' .
self assert: _var1 equals: 0 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_uKeAXiM|.c9' .
self assert: _var6 equals: 0 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test18 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'giM|.cP'.
_var1 := 101.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var2 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 101 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 101 .
self assert: _var0 equals: 'giM|.cP' .
self assert: _var1 equals: 101 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_giM|.cP' .
self assert: _var6 equals: 101 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test19 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 't.cv'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: 't.cv' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_t.cv' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test2 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'R4iM|.cO'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: 'R4iM|.cO' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_R4iM|.cO' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test20 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'uKeAXiM|.c9'.
_var1 := 0.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 0 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 0 .
self assert: _var0 equals: 'uKeAXiM|.c9' .
self assert: _var1 equals: 0 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_uKeAXiM|.c9' .
self assert: _var6 equals: 0 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test21 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'giM|.cP'.
_var1 := 100.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self assert: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self assert: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 100 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 100 .
self assert: _var0 equals: 'giM|.cP' .
self assert: _var1 equals: 100 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_giM|.cP' .
self assert: _var6 equals: 100 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test22 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '.c~'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: '.c~' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_.c~' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test23 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '.c~'.
_var1 := 100.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var2 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self assert: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self assert: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 100 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 100 .
self assert: _var0 equals: '.c~' .
self assert: _var1 equals: 100 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_.c~' .
self assert: _var6 equals: 100 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test24 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'NeAXiM|.c.'.
_var1 := 100.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self assert: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self assert: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 100 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 100 .
self assert: _var0 equals: 'NeAXiM|.c.' .
self assert: _var1 equals: 100 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_NeAXiM|.c.' .
self assert: _var6 equals: 100 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test25 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '.c~'.
_var1 := 70.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 70 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 70 .
self assert: _var0 equals: '.c~' .
self assert: _var1 equals: 70 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_.c~' .
self assert: _var6 equals: 70 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test26 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'eAXiM|.c,'.
_var1 := 57.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 57 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 57 .
self assert: _var0 equals: 'eAXiM|.c,' .
self assert: _var1 equals: 57 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_eAXiM|.c,' .
self assert: _var6 equals: 57 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test27 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '6.c1'.
_var1 := 100.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self assert: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self assert: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 100 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 100 .
self assert: _var0 equals: '6.c1' .
self assert: _var1 equals: 100 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_6.c1' .
self assert: _var6 equals: 100 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test28 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '4iM|.c]'.
_var1 := 0.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 0 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 0 .
self assert: _var0 equals: '4iM|.c]' .
self assert: _var1 equals: 0 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_4iM|.c]' .
self assert: _var6 equals: 0 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test29 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'giM|.cP'.
_var1 := 150.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 150 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 150 .
self assert: _var0 equals: 'giM|.cP' .
self assert: _var1 equals: 150 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_giM|.cP' .
self assert: _var6 equals: 150 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test3 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'R4iM|.cO'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: 'R4iM|.cO' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_R4iM|.cO' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test30 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '.c~'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: '.c~' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_.c~' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test4 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '.c~'.
_var1 := 67.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 67 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 67 .
self assert: _var0 equals: '.c~' .
self assert: _var1 equals: 67 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_.c~' .
self assert: _var6 equals: 67 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test5 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '.c~'.
_var1 := 67.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var2 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 67 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 67 .
self assert: _var0 equals: '.c~' .
self assert: _var1 equals: 67 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_.c~' .
self assert: _var6 equals: 67 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test6 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'gR4iM|.c~'.
_var1 := 50.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 50 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 50 .
self assert: _var0 equals: 'gR4iM|.c~' .
self assert: _var1 equals: 50 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_gR4iM|.c~' .
self assert: _var6 equals: 50 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test7 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '.c~'.
_var1 := 67.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var2 idTeacher.
_var5 := _var2 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 67 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 67 .
self assert: _var0 equals: '.c~' .
self assert: _var1 equals: 67 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_.c~' .
self assert: _var6 equals: 67 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test8 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := 'giM|.cP'.
_var1 := 101.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var3 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: 101 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: 101 .
self assert: _var0 equals: 'giM|.cP' .
self assert: _var1 equals: 101 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_giM|.cP' .
self assert: _var6 equals: 101 .

]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test9 [
"Fitness: 
block-coverage: 87.5
"
"This test covers: 
block-coverage
SSPerson:35.714%
SSTeacher:87.5%
"
_var0 := '^4iM|.cO'.
_var1 := -23.
_var2 := SSTeacher name: _var0 with: _var1 .
_var3 := _var2 yearsWorkExperience: _var1 .
_var4 := _var3 idTeacher.
_var5 := _var3 nickname.
_var6 := _var2 yearsWorkExperience.
self deny: _var0 equals: _var5 .
self deny: _var1 equals: _var4 .
self assert: _var1 equals: _var6 .
self deny: _var4 equals: _var6 .
self assert: _var2 idTeacher equals: 100 .
self assert: _var2 yearsWorkExperience equals: -23 .
self assert: _var3 idTeacher equals: 100 .
self assert: _var3 yearsWorkExperience equals: -23 .
self assert: _var0 equals: '^4iM|.cO' .
self assert: _var1 equals: -23 .
self assert: _var4 equals: 100 .
self assert: _var5 equals: 'teacher_^4iM|.cO' .
self assert: _var6 equals: -23 .

]
