Class {
	#name : #GASSTeacherTest,
	#superclass : #TestCase,
	#category : #'SmallSuiteGenerator-Tests-Generated'
}

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test1 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var1 _var9 _var11 _var13 _var14 _var15 _var8 _var17 _var18 _var19 _var12 _var20 _var21 _var22 _var23 _var24 _var25 _var10 _var26 _var27 _var28 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 6299.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var1 := SSTeacher new.
_var9 := SSTeacher name: _var30 with: _var3.
_var11 := 45.
_var13 := _var2 yearsWorkExperience.
_var14 := _var9 idTeacher.
_var15 := _var9 yearsWorkExperience: _var11.
_var8 := _var9 yearsWorkExperience: _var6.
_var17 := _var9 yearsWorkExperience.
_var18 := SSTeacher name: _var30 with: _var17.
_var19 := _var1 idTeacher.
_var12 := _var15 yearsWorkExperience.
_var20 := SSTeacher name: _var30 with: _var12.
_var21 := _var7 yearsWorkExperience.
_var22 := SSTeacher name: _var30 with: _var17.
_var23 := SSTeacher name: _var30 with: _var3.
_var24 := SSTeacher name: _var30 with: _var17.
_var25 := _var1 nickname.
_var10 := _var22 yearsWorkExperience.
_var26 := _var24 idTeacher.
_var27 := SSTeacher name: _var30 with: _var17.
_var28 := 50 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test10 [
	[ | _var0 _var1 _var3 _var6 _var7 _var8 _var9 _var4 _var10 _var11 _var12 _var30 _var2 _var5 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var25 _var26 _var27 _var28 _var29 |
_var0 := 45.
_var1 := 'Ann'.
_var3 := -40.
_var6 := SSTeacher new.
_var7 := _var6 yearsWorkExperience.
_var8 := _var6 yearsWorkExperience: _var0.
_var9 := _var8 nickname.
_var4 := _var6 nickname.
_var10 := _var6 nickname: _var4.
_var11 := SSTeacher name: _var1 with: _var0.
_var12 := SSTeacher name: _var1 with: _var3.
_var30 := _var6 nickname: _var4.
_var2 := SSTeacher name: _var4 with: _var7.
_var5 := SSTeacher name: _var4 with: _var7.
_var13 := 'teacher_Ann'.
_var14 := _var6 yearsWorkExperience.
_var15 := _var12 yearsWorkExperience: _var14.
_var16 := _var8 yearsWorkExperience.
_var17 := _var11 nickname.
_var18 := _var12 nickname: _var17.
_var19 := _var18 yearsWorkExperience.
_var20 := _var10 idTeacher.
_var21 := _var5 nickname.
_var22 := SSTeacher name: _var1 with: _var7.
_var23 := 'teacher_Ann'.
_var25 := SSTeacher name: _var13 with: _var16.
_var26 := _var25 nickname.
_var27 := _var2 yearsWorkExperience.
_var28 := SSTeacher name: _var13 with: _var7.
_var29 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test11 [
	[ | _var0 _var2 _var3 _var1 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var30 _var26 _var27 _var28 _var29 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var1 := 'Ann'.
_var4 := SSTeacher name: _var1 with: _var0.
_var5 := _var4 yearsWorkExperience: _var3.
_var6 := _var5 nickname.
_var7 := _var2 nickname.
_var8 := _var5 nickname: _var6.
_var9 := SSTeacher name: _var7 with: _var3.
_var10 := SSTeacher name: _var1 with: _var0.
_var11 := 'teacher_Ann'.
_var12 := _var8 idTeacher.
_var13 := _var2 idTeacher.
_var14 := SSTeacher name: _var11 with: _var0.
_var15 := _var2 yearsWorkExperience: _var3.
_var16 := _var5 idTeacher.
_var17 := _var14 yearsWorkExperience: _var3.
_var18 := _var2 yearsWorkExperience.
_var19 := _var15 nickname.
_var20 := SSTeacher name: _var6 with: _var16.
_var21 := _var2 idTeacher.
_var22 := SSTeacher name: _var6 with: _var0.
_var23 := 45.
_var24 := _var20 initialize.
_var25 := _var9 idTeacher.
_var30 := _var2 idTeacher.
_var26 := _var10 yearsWorkExperience.
_var27 := _var2 yearsWorkExperience.
_var28 := SSTeacher name: _var1 with: _var16.
_var29 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test12 [
	[ | _var0 _var3 _var1 _var2 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var32 _var29 _var30 _var33 _var31 |
_var0 := 45.
_var3 := -40.
_var1 := 'teacher_Ann'.
_var2 := SSTeacher name: _var1 with: _var3.
_var4 := _var2 nickname.
_var5 := _var2 yearsWorkExperience.
_var6 := _var2 id: _var0.
_var7 := _var6 yearsWorkExperience.
_var8 := SSTeacher name: _var1 with: _var3.
_var9 := SSTeacher name: _var4 with: _var5.
_var10 := _var9 name: _var4.
_var11 := 'Ann'.
_var12 := _var8 idTeacher.
_var13 := _var9 yearsWorkExperience: _var12.
_var14 := _var8 yearsWorkExperience.
_var15 := _var2 yearsWorkExperience: _var7.
_var16 := _var6 yearsWorkExperience.
_var17 := _var13 nickname.
_var18 := _var8 nickname: _var17.
_var19 := _var10 yearsWorkExperience.
_var20 := SSTeacher name: _var1 with: _var3.
_var21 := _var20 idTeacher.
_var22 := SSTeacher name: _var17 with: _var3.
_var23 := 45.
_var24 := _var18 yearsWorkExperience.
_var25 := _var10 initialize.
_var26 := _var25 yearsWorkExperience: _var24.
_var27 := _var8 idTeacher.
_var28 := _var6 yearsWorkExperience.
_var32 := _var2 yearsWorkExperience: _var7.
_var29 := _var2 yearsWorkExperience.
_var30 := SSTeacher name: _var11 with: _var29.
_var33 := _var25 yearsWorkExperience: _var24.
_var31 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test13 [
	[ | _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 _var31 _var32 |
_var0 := 192.
_var1 := 'Ann'.
_var2 := SSTeacher new.
_var3 := _var2 yearsWorkExperience.
_var4 := _var2 nickname.
_var5 := _var2 yearsWorkExperience.
_var6 := _var2 yearsWorkExperience.
_var7 := _var2 id: _var6.
_var8 := _var7 idTeacher.
_var9 := _var7 name: _var4.
_var10 := _var2 nickname.
_var11 := _var7 nickname: _var1.
_var12 := 100.
_var13 := _var2 idTeacher.
_var14 := _var2 yearsWorkExperience.
_var15 := _var7 idTeacher.
_var16 := _var11 yearsWorkExperience: _var5.
_var17 := _var11 idTeacher.
_var18 := _var2 idTeacher.
_var19 := _var11 idTeacher.
_var20 := _var2 yearsWorkExperience.
_var21 := SSTeacher name: _var1 with: _var14.
_var22 := _var2 yearsWorkExperience: _var6.
_var23 := _var16 yearsWorkExperience.
_var24 := _var7 idTeacher.
_var25 := _var22 nickname.
_var26 := _var16 yearsWorkExperience.
_var27 := _var22 initialize.
_var28 := _var2 idTeacher.
_var29 := _var16 yearsWorkExperience.
_var30 := _var16 idTeacher.
_var31 := SSTeacher name: _var4 with: _var5.
_var32 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test14 [
	[ | _var0 _var1 _var3 _var6 _var7 _var8 _var9 _var4 _var10 _var11 _var12 _var30 _var2 _var5 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := 45.
_var1 := 'Ann'.
_var3 := -40.
_var6 := SSTeacher new.
_var7 := _var6 yearsWorkExperience.
_var8 := _var6 yearsWorkExperience: _var0.
_var9 := _var8 nickname.
_var4 := _var6 nickname.
_var10 := _var6 nickname: _var4.
_var11 := SSTeacher name: _var1 with: _var0.
_var12 := SSTeacher name: _var1 with: _var3.
_var30 := _var6 nickname: _var4.
_var2 := SSTeacher name: _var1 with: _var3.
_var5 := 'Ann'.
_var13 := _var8 idTeacher.
_var14 := _var10 yearsWorkExperience: _var3.
_var15 := _var10 yearsWorkExperience.
_var16 := _var30 nickname.
_var17 := _var11 nickname: _var16.
_var18 := _var11 yearsWorkExperience.
_var19 := SSTeacher name: _var9 with: _var7.
_var20 := _var11 idTeacher.
_var21 := SSTeacher name: _var16 with: _var0.
_var22 := 100.
_var23 := SSTeacher name: _var4 with: _var22.
_var24 := 'teacher_Ann'.
_var25 := _var21 id: _var0.
_var26 := _var17 nickname.
_var27 := _var23 yearsWorkExperience.
_var28 := SSTeacher name: _var9 with: _var27.
_var29 := 45 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test15 [
	[ | _var0 _var1 _var3 _var6 _var7 _var8 _var9 _var4 _var10 _var11 _var12 _var2 _var5 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 45.
_var1 := 'Ann'.
_var3 := -40.
_var6 := SSTeacher new.
_var7 := _var6 yearsWorkExperience.
_var8 := _var6 yearsWorkExperience: _var0.
_var9 := _var8 nickname.
_var4 := _var6 nickname.
_var10 := _var6 nickname: _var4.
_var11 := SSTeacher name: _var1 with: _var0.
_var12 := SSTeacher name: _var1 with: _var3.
_var2 := _var10 yearsWorkExperience: _var0.
_var5 := _var10 yearsWorkExperience.
_var13 := _var12 nickname.
_var14 := _var8 nickname: _var9.
_var15 := _var11 idTeacher.
_var16 := _var10 yearsWorkExperience.
_var17 := SSTeacher name: _var9 with: _var0.
_var18 := SSTeacher name: _var9 with: _var15.
_var19 := _var10 idTeacher.
_var20 := _var17 yearsWorkExperience.
_var21 := SSTeacher name: _var9 with: _var20.
_var22 := _var18 yearsWorkExperience.
_var23 := SSTeacher name: _var9 with: _var20.
_var24 := SSTeacher name: _var1 with: _var7.
_var25 := SSTeacher name: _var4 with: _var0.
_var26 := _var11 nickname.
_var27 := SSTeacher name: _var4 with: _var15.
_var28 := 50 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test16 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var1 _var9 _var10 _var11 _var8 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var31 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 6299.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var1 := SSTeacher name: _var30 with: _var3.
_var9 := SSTeacher name: _var30 with: _var3.
_var10 := SSTeacher name: _var30 with: _var0.
_var11 := 45.
_var8 := _var1 nickname: _var30.
_var12 := _var10 yearsWorkExperience: _var3.
_var13 := _var7 yearsWorkExperience.
_var14 := _var10 nickname.
_var15 := _var12 nickname: _var30.
_var16 := _var8 idTeacher.
_var17 := _var5 yearsWorkExperience.
_var18 := _var2 idTeacher.
_var19 := _var1 yearsWorkExperience.
_var20 := SSTeacher name: _var30 with: _var3.
_var31 := _var10 yearsWorkExperience: _var3.
_var21 := _var10 idTeacher.
_var22 := _var1 nickname.
_var23 := SSTeacher name: _var14 with: _var21.
_var24 := 'Ann'.
_var25 := SSTeacher name: _var24 with: _var6.
_var26 := _var7 name: _var30.
_var27 := _var9 id: _var3.
_var28 := _var2 nickname ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test17 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var1 _var9 _var10 _var11 _var8 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 6299.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var1 := SSTeacher name: _var30 with: _var3.
_var9 := SSTeacher name: _var30 with: _var3.
_var10 := SSTeacher name: _var30 with: _var0.
_var11 := 45.
_var8 := SSTeacher name: _var30 with: _var4.
_var12 := 'Ann'.
_var13 := _var1 idTeacher.
_var14 := _var2 nickname.
_var15 := _var8 nickname: _var12.
_var16 := _var9 yearsWorkExperience.
_var17 := _var2 id: _var0.
_var18 := 50.
_var19 := SSTeacher name: _var12 with: _var11.
_var20 := _var1 nickname.
_var21 := SSTeacher name: _var30 with: _var0.
_var22 := 'teacher_Ann'.
_var23 := SSTeacher name: _var22 with: _var11.
_var24 := SSTeacher name: _var12 with: _var13.
_var25 := _var19 nickname.
_var26 := SSTeacher name: _var12 with: _var13.
_var27 := _var1 yearsWorkExperience: _var3.
_var28 := 45 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test18 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var1 _var9 _var11 _var13 _var14 _var15 _var8 _var16 _var17 _var18 _var19 _var12 _var20 _var21 _var22 _var10 _var23 _var24 _var25 _var26 _var27 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 6299.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var1 := SSTeacher new.
_var9 := SSTeacher name: _var30 with: _var3.
_var11 := 45.
_var13 := _var2 yearsWorkExperience.
_var14 := _var9 idTeacher.
_var15 := _var9 yearsWorkExperience: _var11.
_var8 := _var9 yearsWorkExperience: _var6.
_var16 := _var2 nickname.
_var17 := _var9 yearsWorkExperience.
_var18 := SSTeacher name: _var30 with: _var17.
_var19 := _var1 idTeacher.
_var12 := _var15 idTeacher.
_var20 := SSTeacher name: _var30 with: _var12.
_var21 := _var7 yearsWorkExperience.
_var22 := SSTeacher name: _var30 with: _var17.
_var10 := SSTeacher name: _var16 with: _var12.
_var23 := _var9 id: _var21.
_var24 := SSTeacher name: _var30 with: _var3.
_var25 := _var1 nickname: _var30.
_var26 := _var1 nickname.
_var27 := 50 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test19 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var1 _var9 _var10 _var11 _var8 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 6299.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var1 := SSTeacher name: _var30 with: _var3.
_var9 := SSTeacher name: _var30 with: _var3.
_var10 := SSTeacher name: _var30 with: _var0.
_var11 := 45.
_var8 := 'teacher_Ann'.
_var12 := _var7 idTeacher.
_var13 := SSTeacher name: _var30 with: _var11.
_var14 := _var7 yearsWorkExperience: _var6.
_var15 := _var1 nickname.
_var16 := _var2 idTeacher.
_var17 := SSTeacher name: _var15 with: _var4.
_var18 := SSTeacher name: _var30 with: _var0.
_var20 := _var18 yearsWorkExperience.
_var21 := SSTeacher name: _var15 with: _var0.
_var22 := _var7 yearsWorkExperience.
_var23 := SSTeacher name: _var8 with: _var11.
_var24 := SSTeacher name: _var15 with: _var20.
_var25 := SSTeacher name: _var30 with: _var16.
_var26 := _var1 nickname.
_var27 := SSTeacher name: _var8 with: _var11.
_var28 := 50 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test2 [
	[ | _var0 _var1 _var3 _var6 _var7 _var8 _var9 _var4 _var10 _var11 _var12 _var30 _var2 _var5 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var32 _var21 _var22 _var23 _var24 _var25 _var26 _var31 _var27 _var28 |
_var0 := 45.
_var1 := 'Ann'.
_var3 := -40.
_var6 := SSTeacher new.
_var7 := _var6 yearsWorkExperience.
_var8 := _var6 yearsWorkExperience: _var0.
_var9 := _var8 nickname.
_var4 := _var6 nickname.
_var10 := _var6 nickname: _var4.
_var11 := SSTeacher name: _var1 with: _var0.
_var12 := SSTeacher name: _var1 with: _var3.
_var30 := _var6 nickname: _var4.
_var2 := SSTeacher name: _var1 with: _var3.
_var5 := 'Ann'.
_var13 := _var8 idTeacher.
_var14 := _var10 yearsWorkExperience: _var3.
_var15 := _var10 yearsWorkExperience.
_var16 := _var30 nickname.
_var17 := _var11 nickname: _var16.
_var18 := _var11 yearsWorkExperience.
_var19 := SSTeacher name: _var9 with: _var7.
_var20 := _var11 idTeacher.
_var32 := _var6 nickname.
_var21 := SSTeacher name: _var16 with: _var0.
_var22 := 100.
_var23 := _var2 yearsWorkExperience.
_var24 := _var12 initialize.
_var25 := _var11 idTeacher.
_var26 := SSTeacher name: _var9 with: _var25.
_var31 := SSTeacher name: _var1 with: _var3.
_var27 := _var19 yearsWorkExperience: _var25.
_var28 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test20 [
	[ | _var0 _var2 _var3 _var4 _var30 _var1 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var29 _var27 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var4 := -36.
_var30 := _var2 nickname.
_var1 := _var2 id: _var0.
_var5 := _var1 yearsWorkExperience.
_var6 := _var1 name: _var30.
_var7 := SSTeacher name: _var30 with: _var5.
_var8 := SSTeacher name: _var30 with: _var5.
_var9 := _var8 name: _var30.
_var10 := SSTeacher name: _var30 with: _var4.
_var11 := 'teacher_Ann'.
_var12 := _var10 idTeacher.
_var13 := _var6 nickname.
_var14 := _var1 nickname: _var11.
_var15 := _var7 yearsWorkExperience.
_var16 := _var9 id: _var4.
_var17 := 100.
_var18 := SSTeacher name: _var11 with: _var15.
_var19 := _var10 nickname.
_var20 := SSTeacher name: _var11 with: _var12.
_var21 := 'teacher_Ann'.
_var22 := SSTeacher name: _var30 with: _var15.
_var23 := _var20 id: _var12.
_var24 := SSTeacher name: _var11 with: _var17.
_var25 := _var22 nickname: _var30.
_var26 := _var16 nickname.
_var29 := _var16 nickname.
_var27 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test21 [
	[ | _var0 _var1 _var3 _var6 _var31 _var7 _var8 _var9 _var4 _var10 _var32 _var11 _var12 _var30 _var2 _var5 _var13 _var14 _var15 _var16 _var17 _var33 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 45.
_var1 := 'Ann'.
_var3 := -40.
_var6 := SSTeacher new.
_var31 := _var6 id: _var0.
_var7 := _var6 yearsWorkExperience.
_var8 := _var31 yearsWorkExperience: _var0.
_var9 := _var8 nickname.
_var4 := _var6 nickname.
_var10 := _var6 nickname: _var4.
_var32 := _var6 nickname.
_var11 := SSTeacher name: _var1 with: _var0.
_var12 := SSTeacher name: _var1 with: _var3.
_var30 := _var6 nickname: _var4.
_var2 := _var10 yearsWorkExperience: _var0.
_var5 := _var8 yearsWorkExperience.
_var13 := _var8 idTeacher.
_var14 := _var10 yearsWorkExperience: _var13.
_var15 := _var8 yearsWorkExperience.
_var16 := _var30 nickname.
_var17 := _var8 nickname: _var9.
_var33 := _var6 nickname.
_var18 := _var12 yearsWorkExperience.
_var19 := _var11 idTeacher.
_var20 := _var14 nickname.
_var21 := SSTeacher name: _var16 with: _var3.
_var22 := 'Ann'.
_var23 := SSTeacher name: _var4 with: _var18.
_var24 := SSTeacher name: _var4 with: _var0.
_var25 := _var21 nickname.
_var26 := _var23 yearsWorkExperience.
_var27 := SSTeacher name: _var9 with: _var13.
_var28 := 45 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test22 [
	[ | _var0 _var1 _var2 _var3 _var4 _var5 _var7 _var8 _var9 _var10 _var11 _var12 _var6 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 |
_var0 := 100.
_var1 := 'Ann'.
_var2 := SSTeacher new.
_var3 := 100.
_var4 := 45.
_var5 := SSTeacher new.
_var7 := _var2 yearsWorkExperience: _var3.
_var8 := _var2 nickname.
_var9 := _var2 nickname: _var8.
_var10 := SSTeacher name: _var8 with: _var4.
_var11 := 'Ann'.
_var12 := _var2 idTeacher.
_var6 := SSTeacher name: _var1 with: _var3.
_var13 := SSTeacher name: _var1 with: _var3.
_var14 := 'teacher_Ann'.
_var15 := _var6 nickname.
_var16 := _var9 nickname: _var14.
_var17 := _var13 idTeacher.
_var18 := _var9 yearsWorkExperience.
_var19 := SSTeacher name: _var14 with: _var4.
_var20 := SSTeacher name: _var11 with: _var3.
_var21 := _var6 idTeacher.
_var22 := _var2 nickname.
_var23 := SSTeacher name: _var14 with: _var17.
_var24 := 'teacher_Ann'.
_var25 := _var9 idTeacher.
_var26 := SSTeacher name: _var8 with: _var17.
_var27 := SSTeacher name: _var14 with: _var4.
_var28 := 45.
_var29 := _var13 id: _var25.
_var30 := _var13 id: _var25 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test23 [
	[ | _var0 _var2 _var3 _var29 _var4 _var5 _var1 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var18 _var19 _var20 _var21 _var22 _var17 _var23 _var24 _var25 _var26 _var27 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var29 := _var2 nickname.
_var4 := -36.
_var5 := SSTeacher name: _var29 with: _var0.
_var1 := _var5 yearsWorkExperience.
_var6 := _var2 yearsWorkExperience: _var3.
_var7 := _var5 nickname.
_var8 := _var2 nickname: _var7.
_var9 := SSTeacher name: _var7 with: _var1.
_var10 := 'Ann'.
_var11 := _var6 idTeacher.
_var12 := _var5 yearsWorkExperience: _var4.
_var13 := _var9 yearsWorkExperience.
_var14 := _var5 idTeacher.
_var15 := _var2 yearsWorkExperience: _var11.
_var16 := _var6 yearsWorkExperience.
_var18 := _var6 idTeacher.
_var19 := _var15 nickname.
_var20 := _var15 yearsWorkExperience.
_var21 := SSTeacher name: _var10 with: _var3.
_var22 := SSTeacher name: _var19 with: _var16.
_var17 := _var5 nickname.
_var23 := _var5 yearsWorkExperience.
_var24 := _var21 idTeacher.
_var25 := _var9 idTeacher.
_var26 := SSTeacher name: _var17 with: _var13.
_var27 := 45 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test24 [
	[ | _var0 _var3 _var31 _var4 _var32 _var30 _var5 _var6 _var7 _var1 _var9 _var10 _var11 _var8 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var33 _var28 |
_var0 := 100.
_var3 := 6299.
_var31 := 'Ann'.
_var4 := -36.
_var32 := SSTeacher name: _var31 with: _var4.
_var30 := _var32 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var5 yearsWorkExperience: _var6.
_var1 := SSTeacher name: _var30 with: _var3.
_var9 := SSTeacher name: _var30 with: _var3.
_var10 := SSTeacher name: _var30 with: _var0.
_var11 := 45.
_var8 := SSTeacher name: _var30 with: _var4.
_var12 := 'Ann'.
_var13 := _var1 idTeacher.
_var14 := _var1 yearsWorkExperience: _var11.
_var15 := _var7 yearsWorkExperience.
_var16 := _var14 nickname.
_var17 := _var1 nickname: _var30.
_var18 := _var7 yearsWorkExperience.
_var19 := SSTeacher name: _var12 with: _var13.
_var20 := '''Oteacher_Anx'''.
_var21 := _var17 idTeacher.
_var22 := SSTeacher name: _var30 with: _var4.
_var23 := _var14 id: _var18.
_var24 := SSTeacher name: _var20 with: _var6.
_var25 := _var14 yearsWorkExperience: _var11.
_var26 := _var1 idTeacher.
_var27 := _var5 yearsWorkExperience.
_var33 := _var14 yearsWorkExperience: _var11.
_var28 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test25 [
	[ | _var0 _var3 _var6 _var8 _var2 _var4 _var5 _var7 _var9 _var10 _var11 _var1 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := 45.
_var3 := -40.
_var6 := SSTeacher new.
_var8 := _var6 yearsWorkExperience: _var0.
_var2 := _var8 nickname.
_var4 := _var8 nickname.
_var5 := _var6 nickname: _var2.
_var7 := SSTeacher name: _var2 with: _var3.
_var9 := SSTeacher name: _var2 with: _var3.
_var10 := 'teacher_Ann'.
_var11 := _var9 idTeacher.
_var1 := 100.
_var12 := _var7 yearsWorkExperience.
_var13 := _var9 idTeacher.
_var14 := _var7 yearsWorkExperience: _var3.
_var15 := _var7 yearsWorkExperience: _var13.
_var16 := _var9 yearsWorkExperience.
_var17 := _var8 idTeacher.
_var18 := _var14 nickname.
_var19 := SSTeacher name: _var2 with: _var16.
_var20 := _var7 name: _var10.
_var21 := _var6 nickname.
_var22 := SSTeacher name: _var4 with: _var13.
_var23 := 'teacher_Ann'.
_var24 := _var7 idTeacher.
_var25 := SSTeacher name: _var2 with: _var11.
_var26 := SSTeacher name: _var18 with: _var16.
_var27 := SSTeacher name: _var23 with: _var16.
_var28 := 45.
_var29 := _var7 id: _var3 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test26 [
	[ | _var0 _var1 _var3 _var6 _var8 _var9 _var2 _var4 _var5 _var7 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var27 _var28 |
_var0 := 45.
_var1 := 'Ann'.
_var3 := -40.
_var6 := SSTeacher new.
_var8 := _var6 yearsWorkExperience: _var0.
_var9 := _var8 nickname.
_var2 := _var8 yearsWorkExperience: _var3.
_var4 := _var6 nickname.
_var5 := _var8 nickname.
_var7 := SSTeacher name: _var9 with: _var0.
_var10 := SSTeacher name: _var1 with: _var3.
_var11 := _var8 yearsWorkExperience: _var0.
_var12 := _var2 yearsWorkExperience.
_var13 := _var7 idTeacher.
_var14 := _var10 yearsWorkExperience: _var13.
_var15 := _var11 nickname.
_var16 := _var14 yearsWorkExperience.
_var17 := SSTeacher name: _var5 with: _var13.
_var18 := _var17 idTeacher.
_var19 := _var17 nickname.
_var20 := SSTeacher name: _var19 with: _var18.
_var21 := 'teacher_Ann'.
_var22 := _var10 idTeacher.
_var23 := _var10 yearsWorkExperience: _var3.
_var24 := SSTeacher name: _var5 with: _var0.
_var25 := SSTeacher name: _var15 with: _var22.
_var27 := 50.
_var28 := _var23 id: _var22 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test27 [
	[ | _var0 _var2 _var3 _var4 _var30 _var1 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var4 := -36.
_var30 := _var2 nickname.
_var1 := _var2 id: _var0.
_var5 := _var1 yearsWorkExperience.
_var6 := _var1 name: _var30.
_var7 := SSTeacher name: _var30 with: _var5.
_var8 := SSTeacher name: _var30 with: _var5.
_var9 := _var8 name: _var30.
_var10 := 'Ann'.
_var11 := _var2 idTeacher.
_var12 := SSTeacher name: _var30 with: _var0.
_var13 := _var9 yearsWorkExperience.
_var14 := _var8 nickname.
_var15 := _var1 id: _var0.
_var16 := _var8 id: _var13.
_var17 := 50.
_var18 := SSTeacher name: _var14 with: _var4.
_var19 := 45.
_var20 := SSTeacher name: _var30 with: _var11.
_var21 := _var2 yearsWorkExperience.
_var22 := _var15 initialize.
_var23 := _var9 idTeacher.
_var24 := _var8 idTeacher.
_var25 := SSTeacher name: _var30 with: _var4.
_var26 := SSTeacher name: _var14 with: _var4.
_var27 := 50 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test28 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var1 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var1 := _var7 name: _var30.
_var8 := SSTeacher name: _var30 with: _var6.
_var9 := SSTeacher name: _var30 with: _var3.
_var10 := _var5 name: _var30.
_var11 := 'Ann'.
_var12 := _var9 idTeacher.
_var13 := _var8 yearsWorkExperience: _var0.
_var14 := _var1 yearsWorkExperience: _var4.
_var15 := _var1 nickname.
_var16 := _var7 idTeacher.
_var17 := SSTeacher name: _var30 with: _var12.
_var18 := SSTeacher name: _var11 with: _var6.
_var19 := _var18 idTeacher.
_var20 := _var17 yearsWorkExperience.
_var21 := SSTeacher name: _var15 with: _var0.
_var22 := _var18 idTeacher.
_var23 := SSTeacher name: _var30 with: _var12.
_var24 := SSTeacher name: _var15 with: _var4.
_var25 := SSTeacher name: _var30 with: _var19.
_var26 := _var18 nickname.
_var27 := SSTeacher name: _var11 with: _var20.
_var28 := 45 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test29 [
	[ | _var0 _var2 _var3 _var4 _var30 _var1 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var4 := -36.
_var30 := _var2 nickname.
_var1 := _var2 id: _var0.
_var5 := _var1 yearsWorkExperience.
_var6 := _var1 name: _var30.
_var7 := SSTeacher name: _var30 with: _var5.
_var8 := SSTeacher name: _var30 with: _var5.
_var9 := _var8 name: _var30.
_var10 := 'Ann'.
_var11 := _var2 idTeacher.
_var12 := SSTeacher name: _var30 with: _var0.
_var13 := _var6 yearsWorkExperience: _var5.
_var14 := _var9 yearsWorkExperience: _var5.
_var15 := _var8 yearsWorkExperience.
_var16 := _var2 nickname.
_var17 := _var6 nickname: _var10.
_var18 := _var2 yearsWorkExperience.
_var19 := SSTeacher name: _var30 with: _var18.
_var20 := 'Ann'.
_var21 := _var12 idTeacher.
_var22 := SSTeacher name: _var20 with: _var4.
_var23 := _var6 nickname.
_var24 := _var1 yearsWorkExperience.
_var25 := _var17 idTeacher.
_var26 := _var2 idTeacher.
_var27 := SSTeacher name: _var16 with: _var3.
_var28 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test3 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var1 _var25 _var26 _var27 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 6299.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var8 := _var2 nickname: _var30.
_var9 := SSTeacher name: _var30 with: _var3.
_var10 := SSTeacher name: _var30 with: _var4.
_var11 := 'Ann'.
_var12 := 'Ann'.
_var13 := _var2 idTeacher.
_var14 := _var7 idTeacher.
_var15 := SSTeacher name: _var12 with: _var13.
_var16 := _var15 yearsWorkExperience: _var13.
_var17 := _var7 idTeacher.
_var18 := _var16 yearsWorkExperience: _var17.
_var19 := _var2 yearsWorkExperience.
_var20 := _var16 idTeacher.
_var21 := _var5 nickname.
_var22 := SSTeacher name: _var30 with: _var0.
_var23 := SSTeacher name: _var11 with: _var0.
_var24 := SSTeacher name: _var30 with: _var20.
_var1 := _var23 idTeacher.
_var25 := _var8 yearsWorkExperience.
_var26 := SSTeacher name: _var12 with: _var17.
_var27 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test30 [
	[ | _var0 _var2 _var3 _var4 _var30 _var5 _var6 _var7 _var1 _var9 _var10 _var11 _var8 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 6299.
_var4 := -36.
_var30 := _var2 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var7 := _var2 yearsWorkExperience: _var6.
_var1 := SSTeacher name: _var30 with: _var3.
_var9 := SSTeacher name: _var30 with: _var3.
_var10 := SSTeacher name: _var30 with: _var0.
_var11 := 45.
_var8 := SSTeacher name: _var30 with: _var4.
_var12 := 'Ann'.
_var13 := _var1 idTeacher.
_var14 := _var1 nickname.
_var15 := _var1 idTeacher.
_var16 := _var5 idTeacher.
_var17 := _var7 yearsWorkExperience.
_var18 := SSTeacher name: _var14 with: _var4.
_var19 := _var2 yearsWorkExperience: _var4.
_var20 := _var18 idTeacher.
_var21 := _var8 nickname.
_var22 := _var18 yearsWorkExperience.
_var23 := _var1 initialize.
_var24 := _var2 idTeacher.
_var25 := _var10 yearsWorkExperience.
_var26 := _var2 yearsWorkExperience.
_var27 := SSTeacher name: _var21 with: _var15.
_var28 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test4 [
	[ | _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var30 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := 192.
_var1 := 'Ann'.
_var2 := SSTeacher new.
_var3 := _var2 yearsWorkExperience.
_var4 := _var2 nickname.
_var5 := SSTeacher name: _var4 with: _var3.
_var6 := _var5 nickname.
_var7 := _var2 nickname.
_var9 := _var2 nickname.
_var10 := _var2 nickname.
_var11 := SSTeacher name: _var1 with: _var0.
_var12 := SSTeacher name: _var10 with: _var0.
_var13 := SSTeacher name: _var4 with: _var0.
_var14 := 'Ann'.
_var15 := _var5 idTeacher.
_var16 := _var11 yearsWorkExperience: _var0.
_var17 := _var12 yearsWorkExperience.
_var18 := _var12 nickname.
_var19 := _var11 nickname: _var4.
_var20 := _var5 yearsWorkExperience.
_var21 := SSTeacher name: _var10 with: _var17.
_var22 := SSTeacher name: _var6 with: _var15.
_var30 := _var2 nickname.
_var23 := 45.
_var24 := _var22 yearsWorkExperience.
_var25 := _var21 initialize.
_var26 := _var25 id: _var3.
_var27 := SSTeacher name: _var6 with: _var0.
_var28 := _var16 idTeacher ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test5 [
	[ | _var0 _var1 _var3 _var6 _var7 _var8 _var4 _var5 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 |
_var0 := 45.
_var1 := 'Ann'.
_var3 := -40.
_var6 := SSTeacher new.
_var7 := _var6 yearsWorkExperience.
_var8 := _var6 yearsWorkExperience: _var0.
_var4 := SSTeacher name: _var1 with: _var0.
_var5 := SSTeacher name: _var1 with: _var0.
_var9 := _var5 name: _var1.
_var10 := 'Ann'.
_var11 := _var5 idTeacher.
_var12 := _var8 yearsWorkExperience: _var3.
_var13 := _var4 yearsWorkExperience.
_var14 := _var12 yearsWorkExperience: _var0.
_var15 := _var6 yearsWorkExperience.
_var16 := _var6 nickname.
_var17 := _var5 nickname: _var10.
_var18 := _var4 yearsWorkExperience.
_var19 := SSTeacher name: _var16 with: _var3.
_var20 := _var6 idTeacher.
_var21 := SSTeacher name: _var10 with: _var3.
_var22 := 45.
_var23 := _var6 yearsWorkExperience.
_var24 := _var4 initialize.
_var25 := _var9 yearsWorkExperience: _var13.
_var26 := _var5 idTeacher.
_var27 := _var17 yearsWorkExperience.
_var28 := _var6 yearsWorkExperience.
_var29 := SSTeacher name: _var16 with: _var26.
_var30 := 50 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test6 [
	[ | _var0 _var2 _var3 _var1 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var1 := _var2 nickname.
_var4 := _var2 yearsWorkExperience.
_var5 := _var2 id: _var3.
_var6 := _var2 nickname.
_var7 := _var2 nickname.
_var8 := _var5 nickname: _var7.
_var9 := SSTeacher name: _var6 with: _var3.
_var10 := SSTeacher name: _var1 with: _var4.
_var11 := _var2 nickname: _var6.
_var12 := SSTeacher name: _var6 with: _var0.
_var13 := 'Ann'.
_var14 := _var12 idTeacher.
_var15 := _var12 yearsWorkExperience: _var0.
_var16 := _var8 yearsWorkExperience.
_var17 := _var2 nickname.
_var18 := _var11 nickname: _var13.
_var19 := _var5 yearsWorkExperience.
_var20 := SSTeacher name: _var7 with: _var0.
_var21 := _var9 idTeacher.
_var22 := SSTeacher name: _var6 with: _var19.
_var23 := 100.
_var24 := _var5 yearsWorkExperience.
_var25 := _var15 initialize.
_var26 := _var10 idTeacher.
_var27 := _var12 yearsWorkExperience.
_var28 := _var10 idTeacher.
_var29 := SSTeacher name: _var6 with: _var14.
_var30 := 45 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test7 [
	[ | _var0 _var2 _var31 _var3 _var32 _var4 _var30 _var5 _var6 _var1 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 |
_var0 := 100.
_var2 := SSTeacher new.
_var31 := 'teacher_Ann'.
_var3 := 6299.
_var32 := SSTeacher name: _var31 with: _var3.
_var4 := -36.
_var30 := _var32 nickname.
_var5 := SSTeacher name: _var30 with: _var0.
_var6 := _var5 yearsWorkExperience.
_var1 := _var32 id: _var0.
_var7 := _var1 nickname.
_var8 := _var5 nickname: _var7.
_var9 := 50.
_var10 := _var1 idTeacher.
_var11 := _var2 yearsWorkExperience.
_var12 := _var32 idTeacher.
_var13 := _var1 yearsWorkExperience: _var6.
_var14 := _var13 idTeacher.
_var15 := _var32 yearsWorkExperience.
_var16 := SSTeacher name: _var30 with: _var14.
_var17 := _var8 idTeacher.
_var18 := _var1 yearsWorkExperience.
_var19 := SSTeacher name: _var31 with: _var4.
_var20 := _var2 nickname: _var31.
_var21 := 'Ann'.
_var22 := _var16 name: _var31.
_var23 := _var16 nickname.
_var24 := _var13 yearsWorkExperience.
_var25 := SSTeacher name: _var7 with: _var17.
_var26 := 100 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test8 [
	[ | _var0 _var2 _var3 _var1 _var4 _var5 _var7 _var8 _var9 _var6 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 _var31 _var32 |
_var0 := 100.
_var2 := SSTeacher new.
_var3 := 100.
_var1 := _var2 yearsWorkExperience.
_var4 := _var2 nickname.
_var5 := _var2 yearsWorkExperience.
_var7 := _var2 id: _var5.
_var8 := _var7 yearsWorkExperience.
_var9 := _var2 name: _var4.
_var6 := _var9 yearsWorkExperience: _var3.
_var10 := SSTeacher name: _var4 with: _var8.
_var11 := SSTeacher name: _var4 with: _var0.
_var12 := SSTeacher name: _var4 with: _var3.
_var13 := 45.
_var14 := _var10 yearsWorkExperience.
_var15 := _var7 idTeacher.
_var16 := _var2 yearsWorkExperience: _var5.
_var17 := _var10 yearsWorkExperience: _var0.
_var18 := _var9 nickname.
_var19 := _var17 yearsWorkExperience.
_var20 := SSTeacher name: _var18 with: _var19.
_var21 := _var17 idTeacher.
_var22 := _var10 nickname.
_var23 := SSTeacher name: _var18 with: _var0.
_var24 := 'Ann'.
_var25 := _var10 idTeacher.
_var26 := SSTeacher name: _var4 with: _var3.
_var27 := 'teacher_Ann'.
_var28 := SSTeacher name: _var24 with: _var14.
_var29 := _var26 nickname.
_var30 := _var10 id: _var13.
_var31 := SSTeacher name: _var22 with: _var19.
_var32 := 50 ]
]

{ #category : #'as yet unclassified' }
GASSTeacherTest >> test9 [
	[ | _var0 _var1 _var2 _var3 _var4 _var5 _var7 _var8 _var9 _var10 _var11 _var12 _var6 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 |
_var0 := 100.
_var1 := 'Ann'.
_var2 := SSTeacher new.
_var3 := 100.
_var4 := 45.
_var5 := SSTeacher new.
_var7 := _var2 yearsWorkExperience: _var3.
_var8 := _var2 nickname.
_var9 := _var2 nickname: _var8.
_var10 := SSTeacher name: _var8 with: _var4.
_var11 := 'Ann'.
_var12 := _var2 idTeacher.
_var6 := SSTeacher name: _var8 with: _var12.
_var13 := 'teacher_Ann'.
_var14 := _var7 idTeacher.
_var15 := _var2 yearsWorkExperience: _var3.
_var16 := _var10 yearsWorkExperience.
_var17 := _var15 nickname.
_var18 := _var9 nickname: _var8.
_var19 := _var6 yearsWorkExperience.
_var20 := SSTeacher name: _var13 with: _var16.
_var21 := _var9 idTeacher.
_var22 := SSTeacher name: _var8 with: _var21.
_var23 := 50.
_var24 := _var5 yearsWorkExperience.
_var25 := _var9 initialize.
_var26 := _var5 idTeacher.
_var27 := _var25 yearsWorkExperience.
_var28 := _var15 idTeacher.
_var29 := SSTeacher name: _var13 with: _var24.
_var30 := 50 ]
]
