Class {
	#name : #SGeneratedTestCase,
	#superclass : #TestCase,
	#category : #'SmallSuiteGenerator-Tests-Generated'
}

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test1 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := 'teacher_Ann'.
_var4 := SSTeacher new.
_var5 := SSTeacher new.
_var6 := _var5 initialize.
_var7 := _var0 idTeacher.
_var8 := _var5 yearsWorkExperience: _var2.
_var9 := 45.
_var10 := SSTeacher new.
_var11 := _var0 idTeacher.
_var12 := SSTeacher new.
_var13 := _var12 idTeacher.
_var14 := _var5 yearsWorkExperience: _var13.
_var15 := _var10 initialize.
_var16 := _var8 yearsWorkExperience.
_var17 := SSTeacher new.
_var18 := _var4 yearsWorkExperience: _var7.
_var19 := _var10 yearsWorkExperience.
_var20 := 45.
_var21 := _var0 yearsWorkExperience.
_var22 := _var15 initialize.
_var23 := _var6 initialize.
_var24 := 45.
_var25 := SSTeacher new.
_var26 := SSTeacher new.
_var27 := _var17 nickname.
_var28 := SSTeacher new.
_var29 := SSTeacher new.
self deny: _var9 equals: _var2.
self deny: _var9 equals: _var7.
self deny: _var9 equals: _var19.
self deny: _var9 equals: _var21.
self assert: _var9 equals: _var24.
self deny: _var9 equals: _var1.
self deny: _var9 equals: _var13.
self deny: _var9 equals: _var11.
self assert: _var9 equals: _var20.
self deny: _var9 equals: _var16.
self deny: _var2 equals: _var7.
self assert: _var2 equals: _var19.
self assert: _var2 equals: _var21.
self deny: _var2 equals: _var24.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var13.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var20.
self deny: _var2 equals: _var16.
self deny: _var7 equals: _var19.
self deny: _var7 equals: _var21.
self deny: _var7 equals: _var24.
self deny: _var7 equals: _var1.
self assert: _var7 equals: _var13.
self assert: _var7 equals: _var11.
self deny: _var7 equals: _var20.
self assert: _var7 equals: _var16.
self assert: _var19 equals: _var21.
self deny: _var19 equals: _var24.
self assert: _var19 equals: _var1.
self deny: _var19 equals: _var13.
self deny: _var19 equals: _var11.
self deny: _var19 equals: _var20.
self deny: _var19 equals: _var16.
self deny: _var21 equals: _var24.
self assert: _var21 equals: _var1.
self deny: _var21 equals: _var13.
self deny: _var21 equals: _var11.
self deny: _var21 equals: _var20.
self deny: _var21 equals: _var16.
self deny: _var3 equals: _var27.
self deny: _var24 equals: _var1.
self deny: _var24 equals: _var13.
self deny: _var24 equals: _var11.
self assert: _var24 equals: _var20.
self deny: _var24 equals: _var16.
self deny: _var1 equals: _var13.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var20.
self deny: _var1 equals: _var16.
self assert: _var13 equals: _var11.
self deny: _var13 equals: _var20.
self assert: _var13 equals: _var16.
self deny: _var11 equals: _var20.
self assert: _var11 equals: _var16.
self deny: _var20 equals: _var16.
self assert: _var9 equals: 45.
self assert: _var2 equals: 0.
self assert: _var7 equals: 100.
self assert: _var19 equals: 0.
self assert: _var21 equals: 0.
self assert: _var3 equals: 'teacher_Ann'.
self assert: _var24 equals: 45.
self assert: _var1 equals: 0.
self assert: _var13 equals: 100.
self assert: _var11 equals: 100.
self assert: _var20 equals: 45.
self assert: _var27 equals: 'teacher_1'.
self assert: _var16 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test10 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var31 _var32 _var33 _var34 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 idTeacher.
_var3 := 'teacher_Ann'.
_var4 := SSTeacher new.
_var5 := _var0 yearsWorkExperience.
_var6 := SSTeacher new.
_var7 := _var4 initialize.
_var8 := _var4 idTeacher.
_var9 := _var4 yearsWorkExperience.
_var10 := _var6 yearsWorkExperience.
_var11 := SSTeacher new.
_var12 := SSTeacher new.
_var13 := _var11 idTeacher.
_var14 := _var4 yearsWorkExperience: _var5.
_var15 := _var14 idTeacher.
_var16 := _var6 yearsWorkExperience: _var10.
_var17 := _var16 initialize.
_var18 := SSTeacher new.
_var19 := 100.
_var20 := SSTeacher new.
_var21 := _var18 nickname.
_var22 := SSTeacher new.
_var23 := 'teacher_Ann'.
_var24 := _var18 yearsWorkExperience.
_var25 := _var20 idTeacher.
_var26 := _var0 nickname.
_var27 := _var16 initialize.
_var28 := _var4 initialize.
_var29 := 'teacher_Ann'.
_var31 := _var22 idTeacher.
_var32 := SSTeacher new.
_var33 := _var28 nickname.
_var34 := _var6 idTeacher.
self assert: _var25 equals: _var34.
self deny: _var25 equals: _var9.
self assert: _var25 equals: _var2.
self assert: _var25 equals: _var19.
self deny: _var25 equals: _var5.
self deny: _var25 equals: _var10.
self assert: _var25 equals: _var15.
self deny: _var25 equals: _var24.
self assert: _var25 equals: _var8.
self deny: _var25 equals: _var1.
self assert: _var25 equals: _var13.
self assert: _var25 equals: _var31.
self deny: _var34 equals: _var9.
self assert: _var34 equals: _var2.
self assert: _var34 equals: _var19.
self deny: _var34 equals: _var5.
self deny: _var34 equals: _var10.
self assert: _var34 equals: _var15.
self deny: _var34 equals: _var24.
self assert: _var34 equals: _var8.
self deny: _var34 equals: _var1.
self assert: _var34 equals: _var13.
self assert: _var34 equals: _var31.
self deny: _var9 equals: _var2.
self deny: _var9 equals: _var19.
self assert: _var9 equals: _var5.
self assert: _var9 equals: _var10.
self deny: _var9 equals: _var15.
self assert: _var9 equals: _var24.
self deny: _var9 equals: _var8.
self assert: _var9 equals: _var1.
self deny: _var9 equals: _var13.
self deny: _var9 equals: _var31.
self assert: _var2 equals: _var19.
self deny: _var2 equals: _var5.
self deny: _var2 equals: _var10.
self assert: _var2 equals: _var15.
self deny: _var2 equals: _var24.
self assert: _var2 equals: _var8.
self deny: _var2 equals: _var1.
self assert: _var2 equals: _var13.
self assert: _var2 equals: _var31.
self deny: _var23 equals: _var21.
self deny: _var23 equals: _var26.
self assert: _var23 equals: _var3.
self deny: _var23 equals: _var33.
self assert: _var23 equals: _var29.
self deny: _var19 equals: _var5.
self deny: _var19 equals: _var10.
self assert: _var19 equals: _var15.
self deny: _var19 equals: _var24.
self assert: _var19 equals: _var8.
self deny: _var19 equals: _var1.
self assert: _var19 equals: _var13.
self assert: _var19 equals: _var31.
self assert: _var21 equals: _var26.
self deny: _var21 equals: _var3.
self assert: _var21 equals: _var33.
self deny: _var21 equals: _var29.
self assert: _var5 equals: _var10.
self deny: _var5 equals: _var15.
self assert: _var5 equals: _var24.
self deny: _var5 equals: _var8.
self assert: _var5 equals: _var1.
self deny: _var5 equals: _var13.
self deny: _var5 equals: _var31.
self deny: _var10 equals: _var15.
self assert: _var10 equals: _var24.
self deny: _var10 equals: _var8.
self assert: _var10 equals: _var1.
self deny: _var10 equals: _var13.
self deny: _var10 equals: _var31.
self deny: _var26 equals: _var3.
self assert: _var26 equals: _var33.
self deny: _var26 equals: _var29.
self deny: _var15 equals: _var24.
self assert: _var15 equals: _var8.
self deny: _var15 equals: _var1.
self assert: _var15 equals: _var13.
self assert: _var15 equals: _var31.
self deny: _var3 equals: _var33.
self assert: _var3 equals: _var29.
self deny: _var24 equals: _var8.
self assert: _var24 equals: _var1.
self deny: _var24 equals: _var13.
self deny: _var24 equals: _var31.
self deny: _var33 equals: _var29.
self deny: _var8 equals: _var1.
self assert: _var8 equals: _var13.
self assert: _var8 equals: _var31.
self deny: _var1 equals: _var13.
self deny: _var1 equals: _var31.
self assert: _var13 equals: _var31.
self assert: _var25 equals: 100.
self assert: _var34 equals: 100.
self assert: _var9 equals: 0.
self assert: _var2 equals: 100.
self assert: _var23 equals: 'teacher_Ann'.
self assert: _var19 equals: 100.
self assert: _var21 equals: 'teacher_1'.
self assert: _var5 equals: 0.
self assert: _var10 equals: 0.
self assert: _var26 equals: 'teacher_1'.
self assert: _var15 equals: 100.
self assert: _var3 equals: 'teacher_Ann'.
self assert: _var24 equals: 0.
self assert: _var33 equals: 'teacher_1'.
self assert: _var8 equals: 100.
self assert: _var1 equals: 0.
self assert: _var13 equals: 100.
self assert: _var29 equals: 'teacher_Ann'.
self assert: _var31 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test11 [
| _var0 _var29 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var30 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 |
_var0 := SSTeacher new.
_var29 := SSTeacher new.
_var1 := _var29 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var29 nickname.
_var4 := 45.
_var5 := 'teacher_Ann'.
_var6 := SSTeacher new.
_var7 := _var6 initialize.
_var8 := _var29 initialize.
_var9 := _var0 idTeacher.
_var30 := _var6 initialize.
_var10 := 'teacher_Ann'.
_var11 := _var6 idTeacher.
_var12 := 100.
_var13 := _var8 yearsWorkExperience: _var11.
_var14 := _var7 yearsWorkExperience: _var11.
_var15 := _var29 initialize.
_var16 := SSTeacher new.
_var17 := _var15 yearsWorkExperience: _var12.
_var18 := _var7 yearsWorkExperience.
_var19 := 45.
_var20 := _var16 yearsWorkExperience.
_var21 := _var0 initialize.
_var22 := _var13 initialize.
_var23 := 45.
_var24 := SSTeacher new.
_var25 := SSTeacher new.
_var26 := _var29 nickname.
_var27 := SSTeacher new.
self deny: _var4 equals: _var9.
self deny: _var4 equals: _var2.
self assert: _var4 equals: _var23.
self deny: _var4 equals: _var12.
self assert: _var4 equals: _var19.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var11.
self deny: _var4 equals: _var18.
self deny: _var4 equals: _var20.
self deny: _var9 equals: _var2.
self deny: _var9 equals: _var23.
self assert: _var9 equals: _var12.
self deny: _var9 equals: _var19.
self deny: _var9 equals: _var1.
self assert: _var9 equals: _var11.
self assert: _var9 equals: _var18.
self deny: _var9 equals: _var20.
self deny: _var2 equals: _var23.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var19.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var18.
self assert: _var2 equals: _var20.
self deny: _var23 equals: _var12.
self assert: _var23 equals: _var19.
self deny: _var23 equals: _var1.
self deny: _var23 equals: _var11.
self deny: _var23 equals: _var18.
self deny: _var23 equals: _var20.
self deny: _var12 equals: _var19.
self deny: _var12 equals: _var1.
self assert: _var12 equals: _var11.
self assert: _var12 equals: _var18.
self deny: _var12 equals: _var20.
self deny: _var19 equals: _var1.
self deny: _var19 equals: _var11.
self deny: _var19 equals: _var18.
self deny: _var19 equals: _var20.
self assert: _var5 equals: _var10.
self deny: _var5 equals: _var26.
self deny: _var5 equals: _var3.
self deny: _var10 equals: _var26.
self deny: _var10 equals: _var3.
self assert: _var26 equals: _var3.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var18.
self assert: _var1 equals: _var20.
self assert: _var11 equals: _var18.
self deny: _var11 equals: _var20.
self deny: _var18 equals: _var20.
self assert: _var4 equals: 45.
self assert: _var9 equals: 100.
self assert: _var2 equals: 0.
self assert: _var23 equals: 45.
self assert: _var12 equals: 100.
self assert: _var19 equals: 45.
self assert: _var5 equals: 'teacher_Ann'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var26 equals: 'teacher_1'.
self assert: _var3 equals: 'teacher_1'.
self assert: _var1 equals: 0.
self assert: _var11 equals: 100.
self assert: _var18 equals: 100.
self assert: _var20 equals: 0
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test12 [
| _var0 _var29 _var1 _var2 _var3 _var4 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := SSTeacher new.
_var29 := SSTeacher new.
_var1 := _var29 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var29 nickname.
_var4 := 45.
_var6 := SSTeacher new.
_var7 := _var6 initialize.
_var8 := _var29 idTeacher.
_var9 := _var29 idTeacher.
_var10 := _var7 idTeacher.
_var11 := SSTeacher new.
_var12 := _var7 idTeacher.
_var13 := _var29 yearsWorkExperience: _var4.
_var14 := _var29 nickname.
_var15 := _var13 yearsWorkExperience.
_var16 := SSTeacher new.
_var17 := 100.
_var18 := SSTeacher new.
_var19 := _var13 yearsWorkExperience: _var8.
_var20 := 'teacher_Ann'.
_var21 := _var7 nickname.
_var22 := 'teacher_Ann'.
_var23 := 'teacher_Ann'.
_var24 := _var6 yearsWorkExperience: _var10.
_var25 := _var16 nickname.
_var26 := _var7 yearsWorkExperience: _var10.
_var27 := _var16 yearsWorkExperience: _var2.
_var28 := _var11 yearsWorkExperience: _var2.
self deny: _var4 equals: _var9.
self deny: _var4 equals: _var2.
self deny: _var4 equals: _var12.
self deny: _var4 equals: _var17.
self deny: _var4 equals: _var10.
self assert: _var4 equals: _var15.
self deny: _var4 equals: _var8.
self deny: _var4 equals: _var1.
self assert: _var25 equals: _var14.
self deny: _var25 equals: _var23.
self assert: _var25 equals: _var21.
self assert: _var25 equals: _var3.
self deny: _var25 equals: _var22.
self deny: _var25 equals: _var20.
self deny: _var9 equals: _var2.
self assert: _var9 equals: _var12.
self assert: _var9 equals: _var17.
self assert: _var9 equals: _var10.
self deny: _var9 equals: _var15.
self assert: _var9 equals: _var8.
self deny: _var9 equals: _var1.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var17.
self deny: _var2 equals: _var10.
self deny: _var2 equals: _var15.
self deny: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var14 equals: _var23.
self assert: _var14 equals: _var21.
self assert: _var14 equals: _var3.
self deny: _var14 equals: _var22.
self deny: _var14 equals: _var20.
self deny: _var23 equals: _var21.
self deny: _var23 equals: _var3.
self assert: _var23 equals: _var22.
self assert: _var23 equals: _var20.
self assert: _var12 equals: _var17.
self assert: _var12 equals: _var10.
self deny: _var12 equals: _var15.
self assert: _var12 equals: _var8.
self deny: _var12 equals: _var1.
self assert: _var21 equals: _var3.
self deny: _var21 equals: _var22.
self deny: _var21 equals: _var20.
self assert: _var17 equals: _var10.
self deny: _var17 equals: _var15.
self assert: _var17 equals: _var8.
self deny: _var17 equals: _var1.
self deny: _var10 equals: _var15.
self assert: _var10 equals: _var8.
self deny: _var10 equals: _var1.
self deny: _var15 equals: _var8.
self deny: _var15 equals: _var1.
self deny: _var3 equals: _var22.
self deny: _var3 equals: _var20.
self deny: _var8 equals: _var1.
self assert: _var22 equals: _var20.
self assert: _var4 equals: 45.
self assert: _var25 equals: 'teacher_1'.
self assert: _var9 equals: 100.
self assert: _var2 equals: 0.
self assert: _var14 equals: 'teacher_1'.
self assert: _var23 equals: 'teacher_Ann'.
self assert: _var12 equals: 100.
self assert: _var21 equals: 'teacher_1'.
self assert: _var17 equals: 100.
self assert: _var10 equals: 100.
self assert: _var15 equals: 45.
self assert: _var3 equals: 'teacher_1'.
self assert: _var8 equals: 100.
self assert: _var1 equals: 0.
self assert: _var22 equals: 'teacher_Ann'.
self assert: _var20 equals: 'teacher_Ann'
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test13 [
| _var0 _var1 _var2 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var3 _var27 _var28 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var4 := SSTeacher new.
_var5 := _var0 nickname.
_var6 := _var4 nickname.
_var7 := _var0 initialize.
_var8 := _var7 yearsWorkExperience.
_var9 := SSTeacher new.
_var10 := 'teacher_Ann'.
_var11 := _var9 idTeacher.
_var12 := 45.
_var13 := _var4 yearsWorkExperience: _var1.
_var14 := _var7 nickname.
_var15 := _var0 yearsWorkExperience.
_var16 := SSTeacher new.
_var17 := SSTeacher new.
_var18 := _var0 yearsWorkExperience: _var8.
_var19 := _var17 yearsWorkExperience.
_var20 := 45.
_var21 := 43.
_var22 := _var17 yearsWorkExperience: _var1.
_var23 := _var18 nickname.
_var24 := _var16 initialize.
_var25 := 45.
_var26 := SSTeacher new.
_var3 := _var4 nickname.
_var27 := _var9 idTeacher.
_var28 := 100.
self deny: _var25 equals: _var2.
self deny: _var25 equals: _var19.
self assert: _var25 equals: _var12.
self deny: _var25 equals: _var21.
self deny: _var25 equals: _var28.
self deny: _var25 equals: _var15.
self deny: _var25 equals: _var8.
self deny: _var25 equals: _var1.
self deny: _var25 equals: _var11.
self assert: _var25 equals: _var20.
self deny: _var25 equals: _var27.
self assert: _var2 equals: _var19.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var21.
self deny: _var2 equals: _var28.
self assert: _var2 equals: _var15.
self assert: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var20.
self deny: _var2 equals: _var27.
self assert: _var14 equals: _var23.
self assert: _var14 equals: _var5.
self deny: _var14 equals: _var10.
self assert: _var14 equals: _var3.
self assert: _var14 equals: _var6.
self assert: _var23 equals: _var5.
self deny: _var23 equals: _var10.
self assert: _var23 equals: _var3.
self assert: _var23 equals: _var6.
self deny: _var19 equals: _var12.
self deny: _var19 equals: _var21.
self deny: _var19 equals: _var28.
self assert: _var19 equals: _var15.
self assert: _var19 equals: _var8.
self assert: _var19 equals: _var1.
self deny: _var19 equals: _var11.
self deny: _var19 equals: _var20.
self deny: _var19 equals: _var27.
self deny: _var12 equals: _var21.
self deny: _var12 equals: _var28.
self deny: _var12 equals: _var15.
self deny: _var12 equals: _var8.
self deny: _var12 equals: _var1.
self deny: _var12 equals: _var11.
self assert: _var12 equals: _var20.
self deny: _var12 equals: _var27.
self deny: _var21 equals: _var28.
self deny: _var21 equals: _var15.
self deny: _var21 equals: _var8.
self deny: _var21 equals: _var1.
self deny: _var21 equals: _var11.
self deny: _var21 equals: _var20.
self deny: _var21 equals: _var27.
self deny: _var28 equals: _var15.
self deny: _var28 equals: _var8.
self deny: _var28 equals: _var1.
self assert: _var28 equals: _var11.
self deny: _var28 equals: _var20.
self assert: _var28 equals: _var27.
self deny: _var5 equals: _var10.
self assert: _var5 equals: _var3.
self assert: _var5 equals: _var6.
self deny: _var10 equals: _var3.
self deny: _var10 equals: _var6.
self assert: _var15 equals: _var8.
self assert: _var15 equals: _var1.
self deny: _var15 equals: _var11.
self deny: _var15 equals: _var20.
self deny: _var15 equals: _var27.
self assert: _var3 equals: _var6.
self assert: _var8 equals: _var1.
self deny: _var8 equals: _var11.
self deny: _var8 equals: _var20.
self deny: _var8 equals: _var27.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var20.
self deny: _var1 equals: _var27.
self deny: _var11 equals: _var20.
self assert: _var11 equals: _var27.
self deny: _var20 equals: _var27.
self assert: _var25 equals: 45.
self assert: _var2 equals: 0.
self assert: _var14 equals: 'teacher_1'.
self assert: _var23 equals: 'teacher_1'.
self assert: _var19 equals: 0.
self assert: _var12 equals: 45.
self assert: _var21 equals: 43.
self assert: _var28 equals: 100.
self assert: _var5 equals: 'teacher_1'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var15 equals: 0.
self assert: _var3 equals: 'teacher_1'.
self assert: _var8 equals: 0.
self assert: _var1 equals: 0.
self assert: _var11 equals: 100.
self assert: _var6 equals: 'teacher_1'.
self assert: _var20 equals: 45.
self assert: _var27 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test14 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var13 _var27 _var28 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := 'teacher_Ann'.
_var4 := SSTeacher new.
_var5 := _var0 yearsWorkExperience.
_var6 := _var0 nickname.
_var7 := _var4 initialize.
_var8 := _var4 yearsWorkExperience.
_var9 := SSTeacher new.
_var10 := 'teacher_Ann'.
_var11 := _var4 idTeacher.
_var12 := SSTeacher new.
_var14 := _var9 yearsWorkExperience: _var5.
_var15 := _var9 yearsWorkExperience: _var11.
_var16 := _var9 initialize.
_var17 := _var0 yearsWorkExperience.
_var18 := _var9 initialize.
_var19 := _var4 yearsWorkExperience: _var5.
_var20 := _var0 yearsWorkExperience.
_var21 := 45.
_var22 := _var18 yearsWorkExperience: _var17.
_var23 := _var9 nickname.
_var24 := _var7 initialize.
_var25 := _var7 yearsWorkExperience: _var20.
_var26 := 'teacher_Ann'.
_var13 := SSTeacher new.
_var27 := _var24 nickname.
_var28 := SSTeacher new.
self deny: _var2 equals: _var21.
self assert: _var2 equals: _var17.
self assert: _var2 equals: _var5.
self assert: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self assert: _var2 equals: _var20.
self deny: _var23 equals: _var10.
self deny: _var23 equals: _var26.
self deny: _var23 equals: _var3.
self assert: _var23 equals: _var6.
self assert: _var23 equals: _var27.
self deny: _var21 equals: _var17.
self deny: _var21 equals: _var5.
self deny: _var21 equals: _var8.
self deny: _var21 equals: _var1.
self deny: _var21 equals: _var11.
self deny: _var21 equals: _var20.
self assert: _var17 equals: _var5.
self assert: _var17 equals: _var8.
self assert: _var17 equals: _var1.
self deny: _var17 equals: _var11.
self assert: _var17 equals: _var20.
self assert: _var5 equals: _var8.
self assert: _var5 equals: _var1.
self deny: _var5 equals: _var11.
self assert: _var5 equals: _var20.
self assert: _var10 equals: _var26.
self assert: _var10 equals: _var3.
self deny: _var10 equals: _var6.
self deny: _var10 equals: _var27.
self assert: _var26 equals: _var3.
self deny: _var26 equals: _var6.
self deny: _var26 equals: _var27.
self deny: _var3 equals: _var6.
self deny: _var3 equals: _var27.
self assert: _var8 equals: _var1.
self deny: _var8 equals: _var11.
self assert: _var8 equals: _var20.
self deny: _var1 equals: _var11.
self assert: _var1 equals: _var20.
self deny: _var11 equals: _var20.
self assert: _var6 equals: _var27.
self assert: _var2 equals: 0.
self assert: _var23 equals: 'teacher_1'.
self assert: _var21 equals: 45.
self assert: _var17 equals: 0.
self assert: _var5 equals: 0.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var26 equals: 'teacher_Ann'.
self assert: _var3 equals: 'teacher_Ann'.
self assert: _var8 equals: 0.
self assert: _var1 equals: 0.
self assert: _var11 equals: 100.
self assert: _var6 equals: 'teacher_1'.
self assert: _var20 equals: 0.
self assert: _var27 equals: 'teacher_1'
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test15 [
| _var1 _var30 _var2 _var0 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var31 _var32 _var33 |
_var1 := 45.
_var30 := SSTeacher new.
_var2 := _var30 yearsWorkExperience: _var1.
_var0 := 'teacher_Ann'.
_var3 := SSTeacher new.
_var4 := _var3 yearsWorkExperience.
_var5 := SSTeacher new.
_var6 := _var3 initialize.
_var7 := _var6 idTeacher.
_var8 := _var5 yearsWorkExperience.
_var9 := SSTeacher new.
_var10 := SSTeacher new.
_var11 := _var10 idTeacher.
_var12 := _var6 yearsWorkExperience: _var1.
_var13 := _var12 idTeacher.
_var14 := _var2 yearsWorkExperience: _var13.
_var15 := _var10 initialize.
_var16 := SSTeacher new.
_var17 := 100.
_var18 := SSTeacher new.
_var19 := _var15 nickname.
_var20 := SSTeacher new.
_var21 := 'teacher_Ann'.
_var22 := _var3 yearsWorkExperience.
_var23 := _var6 idTeacher.
_var24 := _var16 nickname.
_var25 := _var12 initialize.
_var26 := _var30 initialize.
_var27 := 'teacher_Ann'.
_var28 := 'teacher_Ann'.
_var29 := _var26 idTeacher.
_var31 := SSTeacher new.
_var32 := _var31 nickname.
_var33 := _var5 idTeacher.
self deny: _var4 equals: _var23.
self deny: _var4 equals: _var7.
self deny: _var4 equals: _var17.
self deny: _var4 equals: _var33.
self assert: _var4 equals: _var8.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var13.
self deny: _var4 equals: _var22.
self deny: _var4 equals: _var29.
self deny: _var4 equals: _var11.
self assert: _var23 equals: _var7.
self assert: _var23 equals: _var17.
self assert: _var23 equals: _var33.
self deny: _var23 equals: _var8.
self deny: _var23 equals: _var1.
self assert: _var23 equals: _var13.
self deny: _var23 equals: _var22.
self assert: _var23 equals: _var29.
self assert: _var23 equals: _var11.
self deny: _var32 equals: _var0.
self assert: _var32 equals: _var19.
self deny: _var32 equals: _var21.
self deny: _var32 equals: _var28.
self assert: _var32 equals: _var24.
self deny: _var32 equals: _var27.
self assert: _var7 equals: _var17.
self assert: _var7 equals: _var33.
self deny: _var7 equals: _var8.
self deny: _var7 equals: _var1.
self assert: _var7 equals: _var13.
self deny: _var7 equals: _var22.
self assert: _var7 equals: _var29.
self assert: _var7 equals: _var11.
self deny: _var0 equals: _var19.
self assert: _var0 equals: _var21.
self assert: _var0 equals: _var28.
self deny: _var0 equals: _var24.
self assert: _var0 equals: _var27.
self deny: _var19 equals: _var21.
self deny: _var19 equals: _var28.
self assert: _var19 equals: _var24.
self deny: _var19 equals: _var27.
self assert: _var21 equals: _var28.
self deny: _var21 equals: _var24.
self assert: _var21 equals: _var27.
self deny: _var28 equals: _var24.
self assert: _var28 equals: _var27.
self assert: _var17 equals: _var33.
self deny: _var17 equals: _var8.
self deny: _var17 equals: _var1.
self assert: _var17 equals: _var13.
self deny: _var17 equals: _var22.
self assert: _var17 equals: _var29.
self assert: _var17 equals: _var11.
self deny: _var24 equals: _var27.
self deny: _var33 equals: _var8.
self deny: _var33 equals: _var1.
self assert: _var33 equals: _var13.
self deny: _var33 equals: _var22.
self assert: _var33 equals: _var29.
self assert: _var33 equals: _var11.
self deny: _var8 equals: _var1.
self deny: _var8 equals: _var13.
self deny: _var8 equals: _var22.
self deny: _var8 equals: _var29.
self deny: _var8 equals: _var11.
self deny: _var1 equals: _var13.
self assert: _var1 equals: _var22.
self deny: _var1 equals: _var29.
self deny: _var1 equals: _var11.
self deny: _var13 equals: _var22.
self assert: _var13 equals: _var29.
self assert: _var13 equals: _var11.
self deny: _var22 equals: _var29.
self deny: _var22 equals: _var11.
self assert: _var29 equals: _var11.
self assert: _var4 equals: 0.
self assert: _var23 equals: 100.
self assert: _var32 equals: 'teacher_1'.
self assert: _var7 equals: 100.
self assert: _var0 equals: 'teacher_Ann'.
self assert: _var19 equals: 'teacher_1'.
self assert: _var21 equals: 'teacher_Ann'.
self assert: _var28 equals: 'teacher_Ann'.
self assert: _var17 equals: 100.
self assert: _var24 equals: 'teacher_1'.
self assert: _var33 equals: 100.
self assert: _var8 equals: 0.
self assert: _var1 equals: 45.
self assert: _var13 equals: 100.
self assert: _var22 equals: 45.
self assert: _var29 equals: 100.
self assert: _var11 equals: 100.
self assert: _var27 equals: 'teacher_Ann'
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test16 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 _var31 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var0 idTeacher.
_var4 := _var0 yearsWorkExperience: _var3.
_var5 := 'teacher_Ann'.
_var6 := _var4 nickname.
_var7 := _var0 initialize.
_var8 := _var7 yearsWorkExperience.
_var9 := SSTeacher new.
_var10 := 'teacher_Ann'.
_var11 := _var7 idTeacher.
_var12 := 100.
_var13 := _var9 yearsWorkExperience: _var1.
_var14 := _var9 nickname.
_var15 := _var13 yearsWorkExperience.
_var16 := SSTeacher new.
_var17 := SSTeacher new.
_var18 := _var0 yearsWorkExperience: _var3.
_var19 := _var18 yearsWorkExperience.
_var20 := 100.
_var21 := _var0 initialize.
_var22 := _var9 initialize.
_var23 := 45.
_var24 := SSTeacher new.
_var25 := SSTeacher new.
_var26 := _var25 initialize.
_var27 := SSTeacher new.
_var28 := _var18 initialize.
_var29 := _var17 yearsWorkExperience: _var15.
_var30 := _var25 nickname.
_var31 := SSTeacher new.
self deny: _var2 equals: _var23.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var19.
self assert: _var2 equals: _var15.
self deny: _var2 equals: _var3.
self assert: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var20.
self assert: _var14 equals: _var30.
self deny: _var14 equals: _var5.
self deny: _var14 equals: _var10.
self assert: _var14 equals: _var6.
self deny: _var23 equals: _var12.
self deny: _var23 equals: _var19.
self deny: _var23 equals: _var15.
self deny: _var23 equals: _var3.
self deny: _var23 equals: _var8.
self deny: _var23 equals: _var1.
self deny: _var23 equals: _var11.
self deny: _var23 equals: _var20.
self assert: _var12 equals: _var19.
self deny: _var12 equals: _var15.
self assert: _var12 equals: _var3.
self deny: _var12 equals: _var8.
self deny: _var12 equals: _var1.
self assert: _var12 equals: _var11.
self assert: _var12 equals: _var20.
self deny: _var19 equals: _var15.
self assert: _var19 equals: _var3.
self deny: _var19 equals: _var8.
self deny: _var19 equals: _var1.
self assert: _var19 equals: _var11.
self assert: _var19 equals: _var20.
self deny: _var30 equals: _var5.
self deny: _var30 equals: _var10.
self assert: _var30 equals: _var6.
self assert: _var5 equals: _var10.
self deny: _var5 equals: _var6.
self deny: _var10 equals: _var6.
self deny: _var15 equals: _var3.
self assert: _var15 equals: _var8.
self assert: _var15 equals: _var1.
self deny: _var15 equals: _var11.
self deny: _var15 equals: _var20.
self deny: _var3 equals: _var8.
self deny: _var3 equals: _var1.
self assert: _var3 equals: _var11.
self assert: _var3 equals: _var20.
self assert: _var8 equals: _var1.
self deny: _var8 equals: _var11.
self deny: _var8 equals: _var20.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var20.
self assert: _var11 equals: _var20.
self assert: _var2 equals: 0.
self assert: _var14 equals: 'teacher_1'.
self assert: _var23 equals: 45.
self assert: _var12 equals: 100.
self assert: _var19 equals: 100.
self assert: _var30 equals: 'teacher_1'.
self assert: _var5 equals: 'teacher_Ann'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var15 equals: 0.
self assert: _var3 equals: 100.
self assert: _var8 equals: 0.
self assert: _var1 equals: 0.
self assert: _var11 equals: 100.
self assert: _var6 equals: 'teacher_1'.
self assert: _var20 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test17 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var0 yearsWorkExperience.
_var4 := _var0 nickname.
_var5 := 45.
_var6 := SSTeacher new.
_var7 := _var0 initialize.
_var8 := _var0 idTeacher.
_var9 := _var7 yearsWorkExperience: _var1.
_var11 := SSTeacher new.
_var12 := SSTeacher new.
_var13 := SSTeacher new.
_var14 := _var6 idTeacher.
_var15 := _var13 nickname.
_var16 := _var11 yearsWorkExperience.
_var17 := SSTeacher new.
_var18 := SSTeacher new.
_var19 := _var0 yearsWorkExperience: _var5.
_var20 := _var9 yearsWorkExperience.
_var21 := _var12 yearsWorkExperience.
_var22 := _var9 initialize.
_var23 := _var11 initialize.
_var24 := _var9 yearsWorkExperience: _var1.
_var25 := '''2teacher_Anx'''.
_var26 := _var13 nickname.
_var27 := _var0 idTeacher.
_var28 := 100.
_var29 := _var6 yearsWorkExperience: _var2.
self deny: _var4 equals: _var25.
self assert: _var4 equals: _var26.
self assert: _var4 equals: _var15.
self deny: _var25 equals: _var26.
self deny: _var25 equals: _var15.
self deny: _var2 equals: _var14.
self assert: _var2 equals: _var21.
self deny: _var2 equals: _var28.
self deny: _var2 equals: _var5.
self assert: _var2 equals: _var3.
self deny: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var20.
self deny: _var2 equals: _var27.
self assert: _var2 equals: _var16.
self deny: _var14 equals: _var21.
self assert: _var14 equals: _var28.
self deny: _var14 equals: _var5.
self deny: _var14 equals: _var3.
self assert: _var14 equals: _var8.
self deny: _var14 equals: _var1.
self deny: _var14 equals: _var20.
self assert: _var14 equals: _var27.
self deny: _var14 equals: _var16.
self deny: _var21 equals: _var28.
self deny: _var21 equals: _var5.
self assert: _var21 equals: _var3.
self deny: _var21 equals: _var8.
self assert: _var21 equals: _var1.
self deny: _var21 equals: _var20.
self deny: _var21 equals: _var27.
self assert: _var21 equals: _var16.
self deny: _var28 equals: _var5.
self deny: _var28 equals: _var3.
self assert: _var28 equals: _var8.
self deny: _var28 equals: _var1.
self deny: _var28 equals: _var20.
self assert: _var28 equals: _var27.
self deny: _var28 equals: _var16.
self deny: _var5 equals: _var3.
self deny: _var5 equals: _var8.
self deny: _var5 equals: _var1.
self assert: _var5 equals: _var20.
self deny: _var5 equals: _var27.
self deny: _var5 equals: _var16.
self assert: _var26 equals: _var15.
self deny: _var3 equals: _var8.
self assert: _var3 equals: _var1.
self deny: _var3 equals: _var20.
self deny: _var3 equals: _var27.
self assert: _var3 equals: _var16.
self deny: _var8 equals: _var1.
self deny: _var8 equals: _var20.
self assert: _var8 equals: _var27.
self deny: _var8 equals: _var16.
self deny: _var1 equals: _var20.
self deny: _var1 equals: _var27.
self assert: _var1 equals: _var16.
self deny: _var20 equals: _var27.
self deny: _var20 equals: _var16.
self deny: _var27 equals: _var16.
self assert: _var4 equals: 'teacher_1'.
self assert: _var25 equals: '''2teacher_Anx'''.
self assert: _var2 equals: 0.
self assert: _var14 equals: 100.
self assert: _var21 equals: 0.
self assert: _var28 equals: 100.
self assert: _var5 equals: 45.
self assert: _var26 equals: 'teacher_1'.
self assert: _var15 equals: 'teacher_1'.
self assert: _var3 equals: 0.
self assert: _var8 equals: 100.
self assert: _var1 equals: 0.
self assert: _var20 equals: 45.
self assert: _var27 equals: 100.
self assert: _var16 equals: 0
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test18 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := 45.
_var3 := 'teacher_Ann'.
_var4 := SSTeacher new.
_var5 := _var4 yearsWorkExperience.
_var6 := SSTeacher new.
_var7 := _var0 initialize.
_var8 := _var6 idTeacher.
_var9 := _var7 yearsWorkExperience: _var5.
_var10 := 45.
_var11 := SSTeacher new.
_var12 := _var6 idTeacher.
_var13 := SSTeacher new.
_var14 := _var11 idTeacher.
_var15 := _var9 yearsWorkExperience: _var14.
_var16 := _var0 initialize.
_var17 := _var13 yearsWorkExperience.
_var18 := _var9 initialize.
_var19 := _var16 yearsWorkExperience: _var14.
_var20 := _var19 yearsWorkExperience.
_var21 := 'teacher_Ann'.
_var22 := _var6 nickname.
_var23 := _var18 initialize.
_var24 := SSTeacher new.
_var25 := _var24 nickname.
_var26 := _var13 yearsWorkExperience: _var8.
_var27 := _var7 nickname.
_var28 := _var23 idTeacher.
_var29 := _var6 idTeacher.
_var30 := _var26 nickname.
self deny: _var25 equals: _var21.
self assert: _var25 equals: _var30.
self deny: _var25 equals: _var3.
self assert: _var25 equals: _var22.
self assert: _var25 equals: _var27.
self deny: _var2 equals: _var14.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var28.
self deny: _var2 equals: _var17.
self deny: _var2 equals: _var5.
self assert: _var2 equals: _var10.
self deny: _var2 equals: _var8.
self deny: _var2 equals: _var1.
self deny: _var2 equals: _var29.
self deny: _var2 equals: _var20.
self assert: _var14 equals: _var12.
self assert: _var14 equals: _var28.
self deny: _var14 equals: _var17.
self deny: _var14 equals: _var5.
self deny: _var14 equals: _var10.
self assert: _var14 equals: _var8.
self deny: _var14 equals: _var1.
self assert: _var14 equals: _var29.
self assert: _var14 equals: _var20.
self assert: _var12 equals: _var28.
self deny: _var12 equals: _var17.
self deny: _var12 equals: _var5.
self deny: _var12 equals: _var10.
self assert: _var12 equals: _var8.
self deny: _var12 equals: _var1.
self assert: _var12 equals: _var29.
self assert: _var12 equals: _var20.
self deny: _var21 equals: _var30.
self assert: _var21 equals: _var3.
self deny: _var21 equals: _var22.
self deny: _var21 equals: _var27.
self deny: _var28 equals: _var17.
self deny: _var28 equals: _var5.
self deny: _var28 equals: _var10.
self assert: _var28 equals: _var8.
self deny: _var28 equals: _var1.
self assert: _var28 equals: _var29.
self assert: _var28 equals: _var20.
self deny: _var30 equals: _var3.
self assert: _var30 equals: _var22.
self assert: _var30 equals: _var27.
self assert: _var17 equals: _var5.
self deny: _var17 equals: _var10.
self deny: _var17 equals: _var8.
self assert: _var17 equals: _var1.
self deny: _var17 equals: _var29.
self deny: _var17 equals: _var20.
self deny: _var5 equals: _var10.
self deny: _var5 equals: _var8.
self assert: _var5 equals: _var1.
self deny: _var5 equals: _var29.
self deny: _var5 equals: _var20.
self deny: _var10 equals: _var8.
self deny: _var10 equals: _var1.
self deny: _var10 equals: _var29.
self deny: _var10 equals: _var20.
self deny: _var3 equals: _var22.
self deny: _var3 equals: _var27.
self deny: _var8 equals: _var1.
self assert: _var8 equals: _var29.
self assert: _var8 equals: _var20.
self deny: _var1 equals: _var29.
self deny: _var1 equals: _var20.
self assert: _var22 equals: _var27.
self assert: _var29 equals: _var20.
self assert: _var25 equals: 'teacher_1'.
self assert: _var2 equals: 45.
self assert: _var14 equals: 100.
self assert: _var12 equals: 100.
self assert: _var21 equals: 'teacher_Ann'.
self assert: _var28 equals: 100.
self assert: _var30 equals: 'teacher_1'.
self assert: _var17 equals: 0.
self assert: _var5 equals: 0.
self assert: _var10 equals: 45.
self assert: _var3 equals: 'teacher_Ann'.
self assert: _var8 equals: 100.
self assert: _var1 equals: 0.
self assert: _var22 equals: 'teacher_1'.
self assert: _var29 equals: 100.
self assert: _var20 equals: 100.
self assert: _var27 equals: 'teacher_1'
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test19 [
| _var0 _var29 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var30 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 |
_var0 := SSTeacher new.
_var29 := SSTeacher new.
_var1 := _var29 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var29 nickname.
_var4 := 45.
_var5 := 'teacher_Ann'.
_var6 := SSTeacher new.
_var7 := _var6 initialize.
_var8 := _var29 initialize.
_var9 := _var0 idTeacher.
_var30 := _var6 initialize.
_var10 := 'teacher_Ann'.
_var11 := _var6 idTeacher.
_var12 := 100.
_var13 := _var8 yearsWorkExperience: _var11.
_var14 := _var7 yearsWorkExperience: _var11.
_var15 := _var0 initialize.
_var16 := 45.
_var17 := SSTeacher new.
_var18 := _var14 yearsWorkExperience: _var1.
_var19 := 45.
_var20 := _var30 yearsWorkExperience: _var2.
_var21 := _var8 nickname.
_var22 := _var13 initialize.
_var23 := 1396.
_var24 := SSTeacher new.
_var25 := SSTeacher new.
_var26 := _var18 nickname.
_var27 := SSTeacher new.
self deny: _var4 equals: _var9.
self deny: _var4 equals: _var2.
self deny: _var4 equals: _var23.
self deny: _var4 equals: _var12.
self assert: _var4 equals: _var19.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var11.
self assert: _var4 equals: _var16.
self deny: _var9 equals: _var2.
self deny: _var9 equals: _var23.
self assert: _var9 equals: _var12.
self deny: _var9 equals: _var19.
self deny: _var9 equals: _var1.
self assert: _var9 equals: _var11.
self deny: _var9 equals: _var16.
self deny: _var2 equals: _var23.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var19.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var16.
self deny: _var23 equals: _var12.
self deny: _var23 equals: _var19.
self deny: _var23 equals: _var1.
self deny: _var23 equals: _var11.
self deny: _var23 equals: _var16.
self deny: _var12 equals: _var19.
self deny: _var12 equals: _var1.
self assert: _var12 equals: _var11.
self deny: _var12 equals: _var16.
self deny: _var19 equals: _var1.
self deny: _var19 equals: _var11.
self assert: _var19 equals: _var16.
self deny: _var21 equals: _var5.
self deny: _var21 equals: _var10.
self assert: _var21 equals: _var26.
self assert: _var21 equals: _var3.
self assert: _var5 equals: _var10.
self deny: _var5 equals: _var26.
self deny: _var5 equals: _var3.
self deny: _var10 equals: _var26.
self deny: _var10 equals: _var3.
self assert: _var26 equals: _var3.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var16.
self deny: _var11 equals: _var16.
self assert: _var4 equals: 45.
self assert: _var9 equals: 100.
self assert: _var2 equals: 0.
self assert: _var23 equals: 1396.
self assert: _var12 equals: 100.
self assert: _var19 equals: 45.
self assert: _var21 equals: 'teacher_1'.
self assert: _var5 equals: 'teacher_Ann'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var26 equals: 'teacher_1'.
self assert: _var3 equals: 'teacher_1'.
self assert: _var1 equals: 0.
self assert: _var11 equals: 100.
self assert: _var16 equals: 45
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test2 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := 'teacher_Ann'.
_var4 := SSTeacher new.
_var5 := _var0 yearsWorkExperience.
_var6 := _var0 idTeacher.
_var7 := _var4 nickname.
_var8 := _var0 initialize.
_var9 := 'teacher_Ann'.
_var10 := _var8 idTeacher.
_var11 := 9501.
_var12 := _var4 yearsWorkExperience: _var2.
_var13 := _var12 nickname.
_var14 := _var0 yearsWorkExperience.
_var15 := SSTeacher new.
_var16 := SSTeacher new.
_var17 := _var16 yearsWorkExperience: _var5.
_var18 := _var8 yearsWorkExperience.
_var19 := 45.
_var20 := _var16 yearsWorkExperience.
_var21 := _var15 yearsWorkExperience: _var11.
_var22 := _var15 nickname.
_var23 := _var0 initialize.
_var24 := _var12 yearsWorkExperience: _var20.
_var25 := 'teacher_Ann'.
_var26 := _var17 nickname.
_var27 := _var17 idTeacher.
_var28 := 100.
self assert: _var25 equals: _var9.
self deny: _var25 equals: _var7.
self deny: _var25 equals: _var26.
self assert: _var25 equals: _var3.
self deny: _var25 equals: _var13.
self deny: _var25 equals: _var22.
self deny: _var9 equals: _var7.
self deny: _var9 equals: _var26.
self assert: _var9 equals: _var3.
self deny: _var9 equals: _var13.
self deny: _var9 equals: _var22.
self assert: _var2 equals: _var14.
self deny: _var2 equals: _var19.
self deny: _var2 equals: _var28.
self assert: _var2 equals: _var5.
self deny: _var2 equals: _var10.
self assert: _var2 equals: _var1.
self assert: _var2 equals: _var18.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var6.
self assert: _var2 equals: _var20.
self deny: _var2 equals: _var27.
self deny: _var14 equals: _var19.
self deny: _var14 equals: _var28.
self assert: _var14 equals: _var5.
self deny: _var14 equals: _var10.
self assert: _var14 equals: _var1.
self assert: _var14 equals: _var18.
self deny: _var14 equals: _var11.
self deny: _var14 equals: _var6.
self assert: _var14 equals: _var20.
self deny: _var14 equals: _var27.
self assert: _var7 equals: _var26.
self deny: _var7 equals: _var3.
self assert: _var7 equals: _var13.
self assert: _var7 equals: _var22.
self deny: _var19 equals: _var28.
self deny: _var19 equals: _var5.
self deny: _var19 equals: _var10.
self deny: _var19 equals: _var1.
self deny: _var19 equals: _var18.
self deny: _var19 equals: _var11.
self deny: _var19 equals: _var6.
self deny: _var19 equals: _var20.
self deny: _var19 equals: _var27.
self deny: _var28 equals: _var5.
self assert: _var28 equals: _var10.
self deny: _var28 equals: _var1.
self deny: _var28 equals: _var18.
self deny: _var28 equals: _var11.
self assert: _var28 equals: _var6.
self deny: _var28 equals: _var20.
self assert: _var28 equals: _var27.
self deny: _var5 equals: _var10.
self assert: _var5 equals: _var1.
self assert: _var5 equals: _var18.
self deny: _var5 equals: _var11.
self deny: _var5 equals: _var6.
self assert: _var5 equals: _var20.
self deny: _var5 equals: _var27.
self deny: _var10 equals: _var1.
self deny: _var10 equals: _var18.
self deny: _var10 equals: _var11.
self assert: _var10 equals: _var6.
self deny: _var10 equals: _var20.
self assert: _var10 equals: _var27.
self deny: _var26 equals: _var3.
self assert: _var26 equals: _var13.
self assert: _var26 equals: _var22.
self deny: _var3 equals: _var13.
self deny: _var3 equals: _var22.
self assert: _var1 equals: _var18.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var6.
self assert: _var1 equals: _var20.
self deny: _var1 equals: _var27.
self assert: _var13 equals: _var22.
self deny: _var18 equals: _var11.
self deny: _var18 equals: _var6.
self assert: _var18 equals: _var20.
self deny: _var18 equals: _var27.
self deny: _var11 equals: _var6.
self deny: _var11 equals: _var20.
self deny: _var11 equals: _var27.
self deny: _var6 equals: _var20.
self assert: _var6 equals: _var27.
self deny: _var20 equals: _var27.
self assert: _var25 equals: 'teacher_Ann'.
self assert: _var9 equals: 'teacher_Ann'.
self assert: _var2 equals: 0.
self assert: _var14 equals: 0.
self assert: _var7 equals: 'teacher_1'.
self assert: _var19 equals: 45.
self assert: _var28 equals: 100.
self assert: _var5 equals: 0.
self assert: _var10 equals: 100.
self assert: _var26 equals: 'teacher_1'.
self assert: _var3 equals: 'teacher_Ann'.
self assert: _var1 equals: 0.
self assert: _var13 equals: 'teacher_1'.
self assert: _var22 equals: 'teacher_1'.
self assert: _var18 equals: 0.
self assert: _var11 equals: 9501.
self assert: _var6 equals: 100.
self assert: _var20 equals: 0.
self assert: _var27 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test20 [
| _var0 _var1 _var2 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var3 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var4 := SSTeacher new.
_var5 := _var0 nickname.
_var6 := _var4 nickname.
_var7 := _var0 initialize.
_var8 := _var7 yearsWorkExperience.
_var9 := SSTeacher new.
_var10 := 'teacher_Ann'.
_var11 := _var9 idTeacher.
_var12 := 45.
_var13 := _var4 yearsWorkExperience: _var1.
_var14 := _var7 nickname.
_var15 := _var0 yearsWorkExperience.
_var16 := SSTeacher new.
_var17 := SSTeacher new.
_var18 := _var0 yearsWorkExperience: _var8.
_var19 := _var17 yearsWorkExperience.
_var20 := 45.
_var3 := 'teacher_Ann'.
_var21 := _var18 nickname.
_var22 := 'teacher_Ann'.
_var23 := 'teacher_Ann'.
_var24 := _var18 yearsWorkExperience: _var15.
_var25 := _var13 nickname.
_var26 := _var0 yearsWorkExperience: _var15.
_var27 := _var7 yearsWorkExperience: _var8.
_var28 := _var9 yearsWorkExperience: _var1.
self assert: _var25 equals: _var14.
self deny: _var25 equals: _var23.
self assert: _var25 equals: _var21.
self assert: _var25 equals: _var5.
self deny: _var25 equals: _var10.
self deny: _var25 equals: _var3.
self deny: _var25 equals: _var22.
self assert: _var25 equals: _var6.
self assert: _var2 equals: _var19.
self deny: _var2 equals: _var12.
self assert: _var2 equals: _var15.
self assert: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var20.
self deny: _var14 equals: _var23.
self assert: _var14 equals: _var21.
self assert: _var14 equals: _var5.
self deny: _var14 equals: _var10.
self deny: _var14 equals: _var3.
self deny: _var14 equals: _var22.
self assert: _var14 equals: _var6.
self deny: _var23 equals: _var21.
self deny: _var23 equals: _var5.
self assert: _var23 equals: _var10.
self assert: _var23 equals: _var3.
self assert: _var23 equals: _var22.
self deny: _var23 equals: _var6.
self deny: _var19 equals: _var12.
self assert: _var19 equals: _var15.
self assert: _var19 equals: _var8.
self assert: _var19 equals: _var1.
self deny: _var19 equals: _var11.
self deny: _var19 equals: _var20.
self deny: _var12 equals: _var15.
self deny: _var12 equals: _var8.
self deny: _var12 equals: _var1.
self deny: _var12 equals: _var11.
self assert: _var12 equals: _var20.
self assert: _var21 equals: _var5.
self deny: _var21 equals: _var10.
self deny: _var21 equals: _var3.
self deny: _var21 equals: _var22.
self assert: _var21 equals: _var6.
self deny: _var5 equals: _var10.
self deny: _var5 equals: _var3.
self deny: _var5 equals: _var22.
self assert: _var5 equals: _var6.
self assert: _var10 equals: _var3.
self assert: _var10 equals: _var22.
self deny: _var10 equals: _var6.
self assert: _var15 equals: _var8.
self assert: _var15 equals: _var1.
self deny: _var15 equals: _var11.
self deny: _var15 equals: _var20.
self assert: _var3 equals: _var22.
self deny: _var3 equals: _var6.
self assert: _var8 equals: _var1.
self deny: _var8 equals: _var11.
self deny: _var8 equals: _var20.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var20.
self deny: _var22 equals: _var6.
self deny: _var11 equals: _var20.
self assert: _var25 equals: 'teacher_1'.
self assert: _var2 equals: 0.
self assert: _var14 equals: 'teacher_1'.
self assert: _var23 equals: 'teacher_Ann'.
self assert: _var19 equals: 0.
self assert: _var12 equals: 45.
self assert: _var21 equals: 'teacher_1'.
self assert: _var5 equals: 'teacher_1'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var15 equals: 0.
self assert: _var3 equals: 'teacher_Ann'.
self assert: _var8 equals: 0.
self assert: _var1 equals: 0.
self assert: _var22 equals: 'teacher_Ann'.
self assert: _var11 equals: 100.
self assert: _var6 equals: 'teacher_1'.
self assert: _var20 equals: 45
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test21 [
| _var0 _var1 _var2 _var4 _var5 _var6 _var7 _var8 _var3 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var31 _var27 _var28 _var30 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var4 := SSTeacher new.
_var5 := _var0 nickname.
_var6 := _var4 nickname.
_var7 := _var0 initialize.
_var8 := _var7 yearsWorkExperience.
_var3 := _var0 yearsWorkExperience.
_var9 := SSTeacher new.
_var10 := 'teacher_Ann'.
_var11 := _var0 idTeacher.
_var12 := SSTeacher new.
_var13 := _var12 nickname.
_var14 := _var7 yearsWorkExperience: _var3.
_var15 := _var9 idTeacher.
_var16 := _var0 yearsWorkExperience: _var1.
_var17 := _var7 initialize.
_var18 := _var7 yearsWorkExperience: _var8.
_var19 := 45.
_var20 := _var4 idTeacher.
_var21 := _var14 yearsWorkExperience.
_var22 := _var18 initialize.
_var23 := _var4 initialize.
_var24 := 45.
_var25 := SSTeacher new.
_var26 := SSTeacher new.
_var31 := _var7 yearsWorkExperience.
_var27 := SSTeacher new.
_var28 := _var17 nickname.
_var30 := _var0 initialize.
_var29 := SSTeacher new.
self deny: _var2 equals: _var19.
self assert: _var2 equals: _var21.
self deny: _var2 equals: _var15.
self assert: _var2 equals: _var3.
self deny: _var2 equals: _var24.
self assert: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self assert: _var2 equals: _var31.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var20.
self deny: _var19 equals: _var21.
self deny: _var19 equals: _var15.
self deny: _var19 equals: _var3.
self assert: _var19 equals: _var24.
self deny: _var19 equals: _var8.
self deny: _var19 equals: _var1.
self deny: _var19 equals: _var31.
self deny: _var19 equals: _var11.
self deny: _var19 equals: _var20.
self deny: _var21 equals: _var15.
self assert: _var21 equals: _var3.
self deny: _var21 equals: _var24.
self assert: _var21 equals: _var8.
self assert: _var21 equals: _var1.
self assert: _var21 equals: _var31.
self deny: _var21 equals: _var11.
self deny: _var21 equals: _var20.
self assert: _var28 equals: _var5.
self deny: _var28 equals: _var10.
self assert: _var28 equals: _var13.
self assert: _var28 equals: _var6.
self deny: _var5 equals: _var10.
self assert: _var5 equals: _var13.
self assert: _var5 equals: _var6.
self deny: _var10 equals: _var13.
self deny: _var10 equals: _var6.
self deny: _var15 equals: _var3.
self deny: _var15 equals: _var24.
self deny: _var15 equals: _var8.
self deny: _var15 equals: _var1.
self deny: _var15 equals: _var31.
self assert: _var15 equals: _var11.
self assert: _var15 equals: _var20.
self deny: _var3 equals: _var24.
self assert: _var3 equals: _var8.
self assert: _var3 equals: _var1.
self assert: _var3 equals: _var31.
self deny: _var3 equals: _var11.
self deny: _var3 equals: _var20.
self deny: _var24 equals: _var8.
self deny: _var24 equals: _var1.
self deny: _var24 equals: _var31.
self deny: _var24 equals: _var11.
self deny: _var24 equals: _var20.
self assert: _var8 equals: _var1.
self assert: _var8 equals: _var31.
self deny: _var8 equals: _var11.
self deny: _var8 equals: _var20.
self assert: _var1 equals: _var31.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var20.
self assert: _var13 equals: _var6.
self deny: _var31 equals: _var11.
self deny: _var31 equals: _var20.
self assert: _var11 equals: _var20.
self assert: _var2 equals: 0.
self assert: _var19 equals: 45.
self assert: _var21 equals: 0.
self assert: _var28 equals: 'teacher_1'.
self assert: _var5 equals: 'teacher_1'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var15 equals: 100.
self assert: _var3 equals: 0.
self assert: _var24 equals: 45.
self assert: _var8 equals: 0.
self assert: _var1 equals: 0.
self assert: _var13 equals: 'teacher_1'.
self assert: _var31 equals: 0.
self assert: _var11 equals: 100.
self assert: _var6 equals: 'teacher_1'.
self assert: _var20 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test22 [
| _var0 _var1 _var2 _var3 _var4 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 idTeacher.
_var2 := 45.
_var3 := SSTeacher new.
_var4 := SSTeacher new.
_var6 := 'teacher_Ann'.
_var7 := _var4 nickname.
_var8 := _var0 initialize.
_var9 := SSTeacher new.
_var10 := 'teacher_Ann'.
_var11 := _var4 idTeacher.
_var12 := 45.
_var13 := _var3 yearsWorkExperience: _var2.
_var14 := _var0 nickname.
_var15 := _var4 yearsWorkExperience.
_var16 := SSTeacher new.
_var17 := SSTeacher new.
_var18 := _var8 yearsWorkExperience: _var11.
_var19 := _var18 yearsWorkExperience.
_var20 := 45.
_var21 := 100.
_var22 := _var16 yearsWorkExperience: _var12.
_var23 := _var8 nickname.
_var24 := _var22 initialize.
_var25 := 100.
_var26 := SSTeacher new.
_var27 := SSTeacher new.
_var28 := _var16 nickname.
_var29 := SSTeacher new.
self deny: _var25 equals: _var2.
self assert: _var25 equals: _var19.
self deny: _var25 equals: _var12.
self assert: _var25 equals: _var21.
self deny: _var25 equals: _var15.
self assert: _var25 equals: _var1.
self assert: _var25 equals: _var11.
self deny: _var25 equals: _var20.
self deny: _var2 equals: _var19.
self assert: _var2 equals: _var12.
self deny: _var2 equals: _var21.
self deny: _var2 equals: _var15.
self deny: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self assert: _var2 equals: _var20.
self assert: _var14 equals: _var23.
self assert: _var14 equals: _var7.
self assert: _var14 equals: _var28.
self deny: _var14 equals: _var10.
self deny: _var14 equals: _var6.
self assert: _var23 equals: _var7.
self assert: _var23 equals: _var28.
self deny: _var23 equals: _var10.
self deny: _var23 equals: _var6.
self deny: _var19 equals: _var12.
self assert: _var19 equals: _var21.
self deny: _var19 equals: _var15.
self assert: _var19 equals: _var1.
self assert: _var19 equals: _var11.
self deny: _var19 equals: _var20.
self deny: _var12 equals: _var21.
self deny: _var12 equals: _var15.
self deny: _var12 equals: _var1.
self deny: _var12 equals: _var11.
self assert: _var12 equals: _var20.
self assert: _var7 equals: _var28.
self deny: _var7 equals: _var10.
self deny: _var7 equals: _var6.
self deny: _var21 equals: _var15.
self assert: _var21 equals: _var1.
self assert: _var21 equals: _var11.
self deny: _var21 equals: _var20.
self deny: _var28 equals: _var10.
self deny: _var28 equals: _var6.
self assert: _var10 equals: _var6.
self deny: _var15 equals: _var1.
self deny: _var15 equals: _var11.
self deny: _var15 equals: _var20.
self assert: _var1 equals: _var11.
self deny: _var1 equals: _var20.
self deny: _var11 equals: _var20.
self assert: _var25 equals: 100.
self assert: _var2 equals: 45.
self assert: _var14 equals: 'teacher_1'.
self assert: _var23 equals: 'teacher_1'.
self assert: _var19 equals: 100.
self assert: _var12 equals: 45.
self assert: _var7 equals: 'teacher_1'.
self assert: _var21 equals: 100.
self assert: _var28 equals: 'teacher_1'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var15 equals: 0.
self assert: _var1 equals: 100.
self assert: _var11 equals: 100.
self assert: _var6 equals: 'teacher_Ann'.
self assert: _var20 equals: 45
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test23 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var30 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 idTeacher.
_var2 := 45.
_var3 := _var0 idTeacher.
_var4 := SSTeacher new.
_var5 := _var4 nickname.
_var6 := _var0 nickname.
_var7 := _var4 initialize.
_var8 := _var7 yearsWorkExperience.
_var9 := SSTeacher new.
_var10 := 'teacher_Ann'.
_var11 := _var0 idTeacher.
_var12 := 100.
_var13 := _var9 yearsWorkExperience: _var2.
_var14 := _var13 nickname.
_var15 := _var9 idTeacher.
_var16 := _var4 initialize.
_var17 := _var4 initialize.
_var18 := 45.
_var30 := _var9 yearsWorkExperience: _var2.
_var19 := SSTeacher new.
_var20 := _var17 yearsWorkExperience: _var1.
_var21 := 'teacher_Ann'.
_var22 := _var13 nickname.
_var23 := SSTeacher new.
_var24 := _var17 initialize.
_var25 := SSTeacher new.
_var26 := _var19 initialize.
_var27 := _var24 yearsWorkExperience: _var3.
_var28 := _var25 nickname.
_var29 := SSTeacher new.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var15.
self deny: _var2 equals: _var3.
self deny: _var2 equals: _var8.
self deny: _var2 equals: _var1.
self assert: _var2 equals: _var18.
self deny: _var2 equals: _var11.
self deny: _var14 equals: _var21.
self assert: _var14 equals: _var28.
self assert: _var14 equals: _var5.
self deny: _var14 equals: _var10.
self assert: _var14 equals: _var22.
self assert: _var14 equals: _var6.
self assert: _var12 equals: _var15.
self assert: _var12 equals: _var3.
self deny: _var12 equals: _var8.
self assert: _var12 equals: _var1.
self deny: _var12 equals: _var18.
self assert: _var12 equals: _var11.
self deny: _var21 equals: _var28.
self deny: _var21 equals: _var5.
self assert: _var21 equals: _var10.
self deny: _var21 equals: _var22.
self deny: _var21 equals: _var6.
self assert: _var28 equals: _var5.
self deny: _var28 equals: _var10.
self assert: _var28 equals: _var22.
self assert: _var28 equals: _var6.
self deny: _var5 equals: _var10.
self assert: _var5 equals: _var22.
self assert: _var5 equals: _var6.
self deny: _var10 equals: _var22.
self deny: _var10 equals: _var6.
self assert: _var15 equals: _var3.
self deny: _var15 equals: _var8.
self assert: _var15 equals: _var1.
self deny: _var15 equals: _var18.
self assert: _var15 equals: _var11.
self deny: _var3 equals: _var8.
self assert: _var3 equals: _var1.
self deny: _var3 equals: _var18.
self assert: _var3 equals: _var11.
self deny: _var8 equals: _var1.
self deny: _var8 equals: _var18.
self deny: _var8 equals: _var11.
self deny: _var1 equals: _var18.
self assert: _var1 equals: _var11.
self assert: _var22 equals: _var6.
self deny: _var18 equals: _var11.
self assert: _var2 equals: 45.
self assert: _var14 equals: 'teacher_1'.
self assert: _var12 equals: 100.
self assert: _var21 equals: 'teacher_Ann'.
self assert: _var28 equals: 'teacher_1'.
self assert: _var5 equals: 'teacher_1'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var15 equals: 100.
self assert: _var3 equals: 100.
self assert: _var8 equals: 0.
self assert: _var1 equals: 100.
self assert: _var22 equals: 'teacher_1'.
self assert: _var18 equals: 45.
self assert: _var11 equals: 100.
self assert: _var6 equals: 'teacher_1'
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test24 [
| _var1 _var30 _var2 _var3 _var4 _var5 _var0 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var1 := 45.
_var30 := SSTeacher new.
_var2 := _var30 yearsWorkExperience: _var1.
_var3 := _var2 idTeacher.
_var4 := _var30 yearsWorkExperience: _var3.
_var5 := '''^teacher_Anc'''.
_var0 := _var4 yearsWorkExperience.
_var6 := _var4 idTeacher.
_var7 := _var30 yearsWorkExperience: _var1.
_var8 := SSTeacher new.
_var9 := 'teacher_Ann'.
_var10 := _var30 idTeacher.
_var11 := SSTeacher new.
_var12 := SSTeacher new.
_var13 := SSTeacher new.
_var14 := _var2 yearsWorkExperience.
_var15 := SSTeacher new.
_var16 := SSTeacher new.
_var17 := _var2 yearsWorkExperience: _var10.
_var18 := _var11 yearsWorkExperience.
_var19 := 100.
_var20 := 'teacher_Ann'.
_var21 := _var8 nickname.
_var22 := _var7 initialize.
_var23 := _var16 nickname.
_var24 := _var17 yearsWorkExperience: _var1.
_var25 := _var7 nickname.
_var26 := _var13 idTeacher.
_var27 := _var30 idTeacher.
_var28 := _var15 nickname.
self deny: _var25 equals: _var9.
self assert: _var25 equals: _var23.
self assert: _var25 equals: _var21.
self assert: _var25 equals: _var28.
self deny: _var25 equals: _var5.
self deny: _var25 equals: _var20.
self deny: _var9 equals: _var23.
self deny: _var9 equals: _var21.
self deny: _var9 equals: _var28.
self deny: _var9 equals: _var5.
self assert: _var9 equals: _var20.
self deny: _var14 equals: _var0.
self deny: _var14 equals: _var19.
self deny: _var14 equals: _var10.
self deny: _var14 equals: _var26.
self deny: _var14 equals: _var3.
self assert: _var14 equals: _var1.
self deny: _var14 equals: _var6.
self deny: _var14 equals: _var18.
self deny: _var14 equals: _var27.
self assert: _var23 equals: _var21.
self assert: _var23 equals: _var28.
self deny: _var23 equals: _var5.
self deny: _var23 equals: _var20.
self assert: _var0 equals: _var19.
self assert: _var0 equals: _var10.
self assert: _var0 equals: _var26.
self assert: _var0 equals: _var3.
self deny: _var0 equals: _var1.
self assert: _var0 equals: _var6.
self deny: _var0 equals: _var18.
self assert: _var0 equals: _var27.
self assert: _var19 equals: _var10.
self assert: _var19 equals: _var26.
self assert: _var19 equals: _var3.
self deny: _var19 equals: _var1.
self assert: _var19 equals: _var6.
self deny: _var19 equals: _var18.
self assert: _var19 equals: _var27.
self assert: _var21 equals: _var28.
self deny: _var21 equals: _var5.
self deny: _var21 equals: _var20.
self deny: _var28 equals: _var5.
self deny: _var28 equals: _var20.
self deny: _var5 equals: _var20.
self assert: _var10 equals: _var26.
self assert: _var10 equals: _var3.
self deny: _var10 equals: _var1.
self assert: _var10 equals: _var6.
self deny: _var10 equals: _var18.
self assert: _var10 equals: _var27.
self assert: _var26 equals: _var3.
self deny: _var26 equals: _var1.
self assert: _var26 equals: _var6.
self deny: _var26 equals: _var18.
self assert: _var26 equals: _var27.
self deny: _var3 equals: _var1.
self assert: _var3 equals: _var6.
self deny: _var3 equals: _var18.
self assert: _var3 equals: _var27.
self deny: _var1 equals: _var6.
self deny: _var1 equals: _var18.
self deny: _var1 equals: _var27.
self deny: _var6 equals: _var18.
self assert: _var6 equals: _var27.
self deny: _var18 equals: _var27.
self assert: _var25 equals: 'teacher_1'.
self assert: _var9 equals: 'teacher_Ann'.
self assert: _var14 equals: 45.
self assert: _var23 equals: 'teacher_1'.
self assert: _var0 equals: 100.
self assert: _var19 equals: 100.
self assert: _var21 equals: 'teacher_1'.
self assert: _var28 equals: 'teacher_1'.
self assert: _var5 equals: '''^teacher_Anc'''.
self assert: _var10 equals: 100.
self assert: _var26 equals: 100.
self assert: _var3 equals: 100.
self assert: _var1 equals: 45.
self assert: _var6 equals: 100.
self assert: _var18 equals: 0.
self assert: _var20 equals: 'teacher_Ann'.
self assert: _var27 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test25 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 idTeacher.
_var2 := 45.
_var3 := SSTeacher new.
_var4 := SSTeacher new.
_var5 := _var3 yearsWorkExperience: _var1.
_var6 := 'teacher_Ann'.
_var7 := _var4 nickname.
_var9 := _var0 yearsWorkExperience.
_var10 := SSTeacher new.
_var11 := 'teacher_Ann'.
_var12 := _var5 idTeacher.
_var13 := 45.
_var14 := _var0 yearsWorkExperience: _var13.
_var15 := _var14 yearsWorkExperience: _var1.
_var16 := _var0 yearsWorkExperience: _var13.
_var17 := 100.
_var18 := SSTeacher new.
_var19 := _var15 yearsWorkExperience: _var1.
_var20 := 'teacher_Ann'.
_var21 := 100.
_var22 := _var10 yearsWorkExperience: _var2.
_var23 := _var0 nickname.
_var24 := _var10 initialize.
_var25 := _var0 yearsWorkExperience: _var1.
_var26 := 'teacher_Ann'.
_var27 := _var15 nickname.
_var28 := _var4 idTeacher.
_var29 := 45.
self deny: _var9 equals: _var2.
self deny: _var9 equals: _var12.
self deny: _var9 equals: _var21.
self deny: _var9 equals: _var28.
self deny: _var9 equals: _var17.
self deny: _var9 equals: _var1.
self deny: _var9 equals: _var13.
self deny: _var9 equals: _var29.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var21.
self deny: _var2 equals: _var28.
self deny: _var2 equals: _var17.
self deny: _var2 equals: _var1.
self assert: _var2 equals: _var13.
self assert: _var2 equals: _var29.
self assert: _var23 equals: _var7.
self deny: _var23 equals: _var26.
self deny: _var23 equals: _var11.
self deny: _var23 equals: _var6.
self deny: _var23 equals: _var20.
self assert: _var23 equals: _var27.
self assert: _var12 equals: _var21.
self assert: _var12 equals: _var28.
self assert: _var12 equals: _var17.
self assert: _var12 equals: _var1.
self deny: _var12 equals: _var13.
self deny: _var12 equals: _var29.
self deny: _var7 equals: _var26.
self deny: _var7 equals: _var11.
self deny: _var7 equals: _var6.
self deny: _var7 equals: _var20.
self assert: _var7 equals: _var27.
self assert: _var21 equals: _var28.
self assert: _var21 equals: _var17.
self assert: _var21 equals: _var1.
self deny: _var21 equals: _var13.
self deny: _var21 equals: _var29.
self assert: _var28 equals: _var17.
self assert: _var28 equals: _var1.
self deny: _var28 equals: _var13.
self deny: _var28 equals: _var29.
self assert: _var17 equals: _var1.
self deny: _var17 equals: _var13.
self deny: _var17 equals: _var29.
self assert: _var26 equals: _var11.
self assert: _var26 equals: _var6.
self assert: _var26 equals: _var20.
self deny: _var26 equals: _var27.
self deny: _var1 equals: _var13.
self deny: _var1 equals: _var29.
self assert: _var13 equals: _var29.
self assert: _var11 equals: _var6.
self assert: _var11 equals: _var20.
self deny: _var11 equals: _var27.
self assert: _var6 equals: _var20.
self deny: _var6 equals: _var27.
self deny: _var20 equals: _var27.
self assert: _var9 equals: 0.
self assert: _var2 equals: 45.
self assert: _var23 equals: 'teacher_1'.
self assert: _var12 equals: 100.
self assert: _var7 equals: 'teacher_1'.
self assert: _var21 equals: 100.
self assert: _var28 equals: 100.
self assert: _var17 equals: 100.
self assert: _var26 equals: 'teacher_Ann'.
self assert: _var1 equals: 100.
self assert: _var13 equals: 45.
self assert: _var29 equals: 45.
self assert: _var11 equals: 'teacher_Ann'.
self assert: _var6 equals: 'teacher_Ann'.
self assert: _var20 equals: 'teacher_Ann'.
self assert: _var27 equals: 'teacher_1'
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test26 [
| _var1 _var30 _var31 _var0 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var32 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 |
_var1 := 45.
_var30 := SSTeacher new.
_var31 := _var30 initialize.
_var0 := _var31 yearsWorkExperience.
_var2 := _var31 idTeacher.
_var3 := SSTeacher new.
_var4 := _var3 yearsWorkExperience.
_var5 := _var3 nickname.
_var6 := _var31 initialize.
_var7 := _var31 idTeacher.
_var8 := 'teacher_Ann'.
_var9 := _var3 idTeacher.
_var10 := SSTeacher new.
_var11 := _var30 nickname.
_var12 := _var3 yearsWorkExperience: _var1.
_var13 := _var10 idTeacher.
_var14 := _var12 yearsWorkExperience: _var9.
_var15 := _var3 initialize.
_var16 := _var31 yearsWorkExperience: _var7.
_var17 := 100.
_var18 := _var6 idTeacher.
_var32 := _var30 nickname.
_var19 := _var31 yearsWorkExperience.
_var20 := _var14 initialize.
_var21 := _var16 initialize.
_var22 := 100.
_var23 := SSTeacher new.
_var24 := SSTeacher new.
_var25 := SSTeacher new.
_var26 := _var10 nickname.
_var27 := SSTeacher new.
self deny: _var4 equals: _var9.
self deny: _var4 equals: _var2.
self deny: _var4 equals: _var7.
self assert: _var4 equals: _var0.
self deny: _var4 equals: _var19.
self deny: _var4 equals: _var17.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var13.
self deny: _var4 equals: _var22.
self deny: _var4 equals: _var18.
self assert: _var9 equals: _var2.
self assert: _var9 equals: _var7.
self deny: _var9 equals: _var0.
self assert: _var9 equals: _var19.
self assert: _var9 equals: _var17.
self deny: _var9 equals: _var1.
self assert: _var9 equals: _var13.
self assert: _var9 equals: _var22.
self assert: _var9 equals: _var18.
self assert: _var2 equals: _var7.
self deny: _var2 equals: _var0.
self assert: _var2 equals: _var19.
self assert: _var2 equals: _var17.
self deny: _var2 equals: _var1.
self assert: _var2 equals: _var13.
self assert: _var2 equals: _var22.
self assert: _var2 equals: _var18.
self assert: _var32 equals: _var5.
self assert: _var32 equals: _var26.
self deny: _var32 equals: _var8.
self assert: _var32 equals: _var11.
self deny: _var7 equals: _var0.
self assert: _var7 equals: _var19.
self assert: _var7 equals: _var17.
self deny: _var7 equals: _var1.
self assert: _var7 equals: _var13.
self assert: _var7 equals: _var22.
self assert: _var7 equals: _var18.
self deny: _var0 equals: _var19.
self deny: _var0 equals: _var17.
self deny: _var0 equals: _var1.
self deny: _var0 equals: _var13.
self deny: _var0 equals: _var22.
self deny: _var0 equals: _var18.
self assert: _var19 equals: _var17.
self deny: _var19 equals: _var1.
self assert: _var19 equals: _var13.
self assert: _var19 equals: _var22.
self assert: _var19 equals: _var18.
self assert: _var5 equals: _var26.
self deny: _var5 equals: _var8.
self assert: _var5 equals: _var11.
self deny: _var17 equals: _var1.
self assert: _var17 equals: _var13.
self assert: _var17 equals: _var22.
self assert: _var17 equals: _var18.
self deny: _var26 equals: _var8.
self assert: _var26 equals: _var11.
self deny: _var8 equals: _var11.
self deny: _var1 equals: _var13.
self deny: _var1 equals: _var22.
self deny: _var1 equals: _var18.
self assert: _var13 equals: _var22.
self assert: _var13 equals: _var18.
self assert: _var22 equals: _var18.
self assert: _var4 equals: 0.
self assert: _var9 equals: 100.
self assert: _var2 equals: 100.
self assert: _var32 equals: 'teacher_1'.
self assert: _var7 equals: 100.
self assert: _var0 equals: 0.
self assert: _var19 equals: 100.
self assert: _var5 equals: 'teacher_1'.
self assert: _var17 equals: 100.
self assert: _var26 equals: 'teacher_1'.
self assert: _var8 equals: 'teacher_Ann'.
self assert: _var1 equals: 45.
self assert: _var13 equals: 100.
self assert: _var22 equals: 100.
self assert: _var11 equals: 'teacher_1'.
self assert: _var18 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test27 [
| _var1 _var30 _var31 _var0 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var32 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var33 _var24 _var25 _var26 _var27 |
_var1 := 141.
_var30 := SSTeacher new.
_var31 := _var30 initialize.
_var0 := 'teacher_Ann'.
_var2 := SSTeacher new.
_var3 := _var30 yearsWorkExperience.
_var4 := _var2 nickname.
_var5 := _var31 initialize.
_var6 := _var5 yearsWorkExperience.
_var7 := SSTeacher new.
_var8 := 'teacher_Ann'.
_var9 := _var31 idTeacher.
_var10 := SSTeacher new.
_var11 := _var30 nickname.
_var12 := _var10 yearsWorkExperience: _var1.
_var13 := _var5 idTeacher.
_var14 := _var12 yearsWorkExperience: _var3.
_var15 := _var10 initialize.
_var16 := _var2 yearsWorkExperience: _var3.
_var32 := _var10 initialize.
_var17 := 45.
_var18 := _var2 idTeacher.
_var19 := _var14 yearsWorkExperience.
_var20 := _var30 initialize.
_var21 := _var14 initialize.
_var22 := 'teacher_Ann'.
_var23 := _var16 yearsWorkExperience: _var19.
_var33 := _var16 yearsWorkExperience: _var19.
_var24 := _var15 yearsWorkExperience.
_var25 := _var7 nickname.
_var26 := _var5 yearsWorkExperience: _var6.
_var27 := _var15 yearsWorkExperience: _var13.
self assert: _var4 equals: _var25.
self deny: _var4 equals: _var0.
self deny: _var4 equals: _var8.
self deny: _var4 equals: _var22.
self assert: _var4 equals: _var11.
self deny: _var25 equals: _var0.
self deny: _var25 equals: _var8.
self deny: _var25 equals: _var22.
self assert: _var25 equals: _var11.
self deny: _var9 equals: _var19.
self deny: _var9 equals: _var17.
self deny: _var9 equals: _var3.
self deny: _var9 equals: _var24.
self deny: _var9 equals: _var1.
self assert: _var9 equals: _var13.
self deny: _var9 equals: _var6.
self assert: _var9 equals: _var18.
self assert: _var0 equals: _var8.
self assert: _var0 equals: _var22.
self deny: _var0 equals: _var11.
self deny: _var19 equals: _var17.
self assert: _var19 equals: _var3.
self assert: _var19 equals: _var24.
self deny: _var19 equals: _var1.
self deny: _var19 equals: _var13.
self assert: _var19 equals: _var6.
self deny: _var19 equals: _var18.
self deny: _var17 equals: _var3.
self deny: _var17 equals: _var24.
self deny: _var17 equals: _var1.
self deny: _var17 equals: _var13.
self deny: _var17 equals: _var6.
self deny: _var17 equals: _var18.
self assert: _var3 equals: _var24.
self deny: _var3 equals: _var1.
self deny: _var3 equals: _var13.
self assert: _var3 equals: _var6.
self deny: _var3 equals: _var18.
self deny: _var24 equals: _var1.
self deny: _var24 equals: _var13.
self assert: _var24 equals: _var6.
self deny: _var24 equals: _var18.
self assert: _var8 equals: _var22.
self deny: _var8 equals: _var11.
self deny: _var1 equals: _var13.
self deny: _var1 equals: _var6.
self deny: _var1 equals: _var18.
self deny: _var13 equals: _var6.
self assert: _var13 equals: _var18.
self deny: _var22 equals: _var11.
self deny: _var6 equals: _var18.
self assert: _var4 equals: 'teacher_1'.
self assert: _var25 equals: 'teacher_1'.
self assert: _var9 equals: 100.
self assert: _var0 equals: 'teacher_Ann'.
self assert: _var19 equals: 0.
self assert: _var17 equals: 45.
self assert: _var3 equals: 0.
self assert: _var24 equals: 0.
self assert: _var8 equals: 'teacher_Ann'.
self assert: _var1 equals: 141.
self assert: _var13 equals: 100.
self assert: _var22 equals: 'teacher_Ann'.
self assert: _var6 equals: 0.
self assert: _var11 equals: 'teacher_1'.
self assert: _var18 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test28 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var0 yearsWorkExperience.
_var4 := _var0 idTeacher.
_var5 := SSTeacher new.
_var6 := _var0 yearsWorkExperience.
_var7 := _var5 nickname.
_var8 := _var5 initialize.
_var10 := 'teacher_Ann'.
_var11 := _var0 idTeacher.
_var12 := _var5 yearsWorkExperience: _var3.
_var13 := _var8 nickname.
_var14 := _var5 yearsWorkExperience.
_var15 := SSTeacher new.
_var16 := SSTeacher new.
_var17 := _var5 yearsWorkExperience: _var3.
_var18 := _var16 yearsWorkExperience.
_var19 := 100.
_var20 := 100.
_var21 := _var5 yearsWorkExperience.
_var22 := _var5 initialize.
_var23 := _var17 initialize.
_var24 := SSTeacher new.
_var25 := _var24 initialize.
_var26 := _var8 yearsWorkExperience: _var1.
_var27 := SSTeacher new.
_var28 := _var0 nickname.
_var29 := SSTeacher new.
self deny: _var4 equals: _var2.
self deny: _var4 equals: _var14.
self assert: _var4 equals: _var19.
self deny: _var4 equals: _var21.
self deny: _var4 equals: _var3.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var18.
self assert: _var4 equals: _var11.
self deny: _var4 equals: _var6.
self assert: _var4 equals: _var20.
self assert: _var2 equals: _var14.
self deny: _var2 equals: _var19.
self assert: _var2 equals: _var21.
self assert: _var2 equals: _var3.
self assert: _var2 equals: _var1.
self assert: _var2 equals: _var18.
self deny: _var2 equals: _var11.
self assert: _var2 equals: _var6.
self deny: _var2 equals: _var20.
self deny: _var14 equals: _var19.
self assert: _var14 equals: _var21.
self assert: _var14 equals: _var3.
self assert: _var14 equals: _var1.
self assert: _var14 equals: _var18.
self deny: _var14 equals: _var11.
self assert: _var14 equals: _var6.
self deny: _var14 equals: _var20.
self deny: _var19 equals: _var21.
self deny: _var19 equals: _var3.
self deny: _var19 equals: _var1.
self deny: _var19 equals: _var18.
self assert: _var19 equals: _var11.
self deny: _var19 equals: _var6.
self assert: _var19 equals: _var20.
self assert: _var7 equals: _var28.
self deny: _var7 equals: _var10.
self assert: _var7 equals: _var13.
self assert: _var21 equals: _var3.
self assert: _var21 equals: _var1.
self assert: _var21 equals: _var18.
self deny: _var21 equals: _var11.
self assert: _var21 equals: _var6.
self deny: _var21 equals: _var20.
self deny: _var28 equals: _var10.
self assert: _var28 equals: _var13.
self deny: _var10 equals: _var13.
self assert: _var3 equals: _var1.
self assert: _var3 equals: _var18.
self deny: _var3 equals: _var11.
self assert: _var3 equals: _var6.
self deny: _var3 equals: _var20.
self assert: _var1 equals: _var18.
self deny: _var1 equals: _var11.
self assert: _var1 equals: _var6.
self deny: _var1 equals: _var20.
self deny: _var18 equals: _var11.
self assert: _var18 equals: _var6.
self deny: _var18 equals: _var20.
self deny: _var11 equals: _var6.
self assert: _var11 equals: _var20.
self deny: _var6 equals: _var20.
self assert: _var4 equals: 100.
self assert: _var2 equals: 0.
self assert: _var14 equals: 0.
self assert: _var19 equals: 100.
self assert: _var7 equals: 'teacher_1'.
self assert: _var21 equals: 0.
self assert: _var28 equals: 'teacher_1'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var3 equals: 0.
self assert: _var1 equals: 0.
self assert: _var13 equals: 'teacher_1'.
self assert: _var18 equals: 0.
self assert: _var11 equals: 100.
self assert: _var6 equals: 0.
self assert: _var20 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test29 [
| _var0 _var29 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var30 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var32 _var31 _var28 |
_var0 := SSTeacher new.
_var29 := SSTeacher new.
_var1 := _var29 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var29 nickname.
_var4 := 45.
_var5 := 'teacher_Ann'.
_var6 := SSTeacher new.
_var7 := _var6 initialize.
_var8 := _var29 initialize.
_var9 := _var0 idTeacher.
_var30 := _var6 initialize.
_var10 := 'teacher_Ann'.
_var11 := _var6 idTeacher.
_var12 := 100.
_var13 := _var8 yearsWorkExperience: _var11.
_var14 := _var7 yearsWorkExperience: _var11.
_var15 := _var0 initialize.
_var16 := 45.
_var17 := SSTeacher new.
_var18 := _var14 yearsWorkExperience: _var4.
_var19 := 'teacher_Ann'.
_var20 := _var14 nickname.
_var21 := 'teacher_Ann'.
_var22 := _var29 initialize.
_var23 := _var13 yearsWorkExperience: _var1.
_var24 := 'teacher_Ann'.
_var25 := _var14 nickname.
_var26 := _var13 idTeacher.
_var27 := _var22 nickname.
_var32 := SSTeacher new.
_var31 := _var29 initialize.
_var28 := 100.
self deny: _var4 equals: _var9.
self deny: _var4 equals: _var2.
self deny: _var4 equals: _var12.
self deny: _var4 equals: _var28.
self deny: _var4 equals: _var26.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var11.
self assert: _var4 equals: _var16.
self deny: _var25 equals: _var19.
self deny: _var25 equals: _var21.
self deny: _var25 equals: _var5.
self deny: _var25 equals: _var10.
self assert: _var25 equals: _var3.
self deny: _var25 equals: _var24.
self assert: _var25 equals: _var20.
self assert: _var25 equals: _var27.
self deny: _var9 equals: _var2.
self assert: _var9 equals: _var12.
self assert: _var9 equals: _var28.
self assert: _var9 equals: _var26.
self deny: _var9 equals: _var1.
self assert: _var9 equals: _var11.
self deny: _var9 equals: _var16.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var28.
self deny: _var2 equals: _var26.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var11.
self deny: _var2 equals: _var16.
self assert: _var12 equals: _var28.
self assert: _var12 equals: _var26.
self deny: _var12 equals: _var1.
self assert: _var12 equals: _var11.
self deny: _var12 equals: _var16.
self assert: _var19 equals: _var21.
self assert: _var19 equals: _var5.
self assert: _var19 equals: _var10.
self deny: _var19 equals: _var3.
self assert: _var19 equals: _var24.
self deny: _var19 equals: _var20.
self deny: _var19 equals: _var27.
self assert: _var21 equals: _var5.
self assert: _var21 equals: _var10.
self deny: _var21 equals: _var3.
self assert: _var21 equals: _var24.
self deny: _var21 equals: _var20.
self deny: _var21 equals: _var27.
self assert: _var28 equals: _var26.
self deny: _var28 equals: _var1.
self assert: _var28 equals: _var11.
self deny: _var28 equals: _var16.
self assert: _var5 equals: _var10.
self deny: _var5 equals: _var3.
self assert: _var5 equals: _var24.
self deny: _var5 equals: _var20.
self deny: _var5 equals: _var27.
self deny: _var10 equals: _var3.
self assert: _var10 equals: _var24.
self deny: _var10 equals: _var20.
self deny: _var10 equals: _var27.
self deny: _var26 equals: _var1.
self assert: _var26 equals: _var11.
self deny: _var26 equals: _var16.
self deny: _var3 equals: _var24.
self assert: _var3 equals: _var20.
self assert: _var3 equals: _var27.
self deny: _var24 equals: _var20.
self deny: _var24 equals: _var27.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var16.
self deny: _var11 equals: _var16.
self assert: _var20 equals: _var27.
self assert: _var4 equals: 45.
self assert: _var25 equals: 'teacher_1'.
self assert: _var9 equals: 100.
self assert: _var2 equals: 0.
self assert: _var12 equals: 100.
self assert: _var19 equals: 'teacher_Ann'.
self assert: _var21 equals: 'teacher_Ann'.
self assert: _var28 equals: 100.
self assert: _var5 equals: 'teacher_Ann'.
self assert: _var10 equals: 'teacher_Ann'.
self assert: _var26 equals: 100.
self assert: _var3 equals: 'teacher_1'.
self assert: _var24 equals: 'teacher_Ann'.
self assert: _var1 equals: 0.
self assert: _var11 equals: 100.
self assert: _var20 equals: 'teacher_1'.
self assert: _var27 equals: 'teacher_1'.
self assert: _var16 equals: 45
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test3 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := 45.
_var3 := _var0 yearsWorkExperience.
_var4 := _var0 nickname.
_var5 := 45.
_var6 := 'teacher_Ann'.
_var7 := _var0 nickname.
_var8 := _var0 initialize.
_var9 := _var0 yearsWorkExperience.
_var10 := SSTeacher new.
_var11 := 'teacher_Ann'.
_var12 := _var8 idTeacher.
_var13 := SSTeacher new.
_var14 := _var10 nickname.
_var15 := _var10 yearsWorkExperience: _var1.
_var16 := _var15 idTeacher.
_var17 := _var10 yearsWorkExperience: _var5.
_var18 := _var13 initialize.
_var19 := _var18 yearsWorkExperience: _var2.
_var20 := 100.
_var21 := _var10 idTeacher.
_var22 := _var8 yearsWorkExperience.
_var23 := _var17 initialize.
_var24 := _var10 initialize.
_var25 := 45.
_var26 := SSTeacher new.
_var27 := SSTeacher new.
_var28 := SSTeacher new.
_var29 := _var8 nickname.
_var30 := SSTeacher new.
self assert: _var4 equals: _var14.
self assert: _var4 equals: _var7.
self assert: _var4 equals: _var29.
self deny: _var4 equals: _var11.
self deny: _var4 equals: _var6.
self deny: _var25 equals: _var9.
self assert: _var25 equals: _var2.
self deny: _var25 equals: _var12.
self deny: _var25 equals: _var21.
self assert: _var25 equals: _var5.
self deny: _var25 equals: _var3.
self deny: _var25 equals: _var1.
self deny: _var25 equals: _var22.
self deny: _var25 equals: _var20.
self deny: _var25 equals: _var16.
self deny: _var9 equals: _var2.
self deny: _var9 equals: _var12.
self deny: _var9 equals: _var21.
self deny: _var9 equals: _var5.
self assert: _var9 equals: _var3.
self assert: _var9 equals: _var1.
self assert: _var9 equals: _var22.
self deny: _var9 equals: _var20.
self deny: _var9 equals: _var16.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var21.
self assert: _var2 equals: _var5.
self deny: _var2 equals: _var3.
self deny: _var2 equals: _var1.
self deny: _var2 equals: _var22.
self deny: _var2 equals: _var20.
self deny: _var2 equals: _var16.
self assert: _var14 equals: _var7.
self assert: _var14 equals: _var29.
self deny: _var14 equals: _var11.
self deny: _var14 equals: _var6.
self assert: _var7 equals: _var29.
self deny: _var7 equals: _var11.
self deny: _var7 equals: _var6.
self assert: _var12 equals: _var21.
self deny: _var12 equals: _var5.
self deny: _var12 equals: _var3.
self deny: _var12 equals: _var1.
self deny: _var12 equals: _var22.
self assert: _var12 equals: _var20.
self assert: _var12 equals: _var16.
self deny: _var21 equals: _var5.
self deny: _var21 equals: _var3.
self deny: _var21 equals: _var1.
self deny: _var21 equals: _var22.
self assert: _var21 equals: _var20.
self assert: _var21 equals: _var16.
self deny: _var5 equals: _var3.
self deny: _var5 equals: _var1.
self deny: _var5 equals: _var22.
self deny: _var5 equals: _var20.
self deny: _var5 equals: _var16.
self assert: _var3 equals: _var1.
self assert: _var3 equals: _var22.
self deny: _var3 equals: _var20.
self deny: _var3 equals: _var16.
self assert: _var1 equals: _var22.
self deny: _var1 equals: _var20.
self deny: _var1 equals: _var16.
self deny: _var22 equals: _var20.
self deny: _var22 equals: _var16.
self deny: _var29 equals: _var11.
self deny: _var29 equals: _var6.
self assert: _var11 equals: _var6.
self assert: _var20 equals: _var16.
self assert: _var4 equals: 'teacher_1'.
self assert: _var25 equals: 45.
self assert: _var9 equals: 0.
self assert: _var2 equals: 45.
self assert: _var14 equals: 'teacher_1'.
self assert: _var7 equals: 'teacher_1'.
self assert: _var12 equals: 100.
self assert: _var21 equals: 100.
self assert: _var5 equals: 45.
self assert: _var3 equals: 0.
self assert: _var1 equals: 0.
self assert: _var22 equals: 0.
self assert: _var29 equals: 'teacher_1'.
self assert: _var11 equals: 'teacher_Ann'.
self assert: _var6 equals: 'teacher_Ann'.
self assert: _var20 equals: 100.
self assert: _var16 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test30 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var31 _var13 _var14 _var16 _var30 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var15 _var24 _var25 _var26 _var27 _var28 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var0 idTeacher.
_var4 := SSTeacher new.
_var5 := _var0 nickname.
_var6 := SSTeacher new.
_var7 := _var6 initialize.
_var8 := _var0 yearsWorkExperience.
_var9 := _var0 yearsWorkExperience: _var3.
_var10 := 45.
_var11 := SSTeacher new.
_var12 := _var7 idTeacher.
_var31 := _var0 yearsWorkExperience.
_var13 := SSTeacher new.
_var14 := _var11 idTeacher.
_var16 := _var0 initialize.
_var30 := _var0 initialize.
_var17 := _var0 yearsWorkExperience.
_var18 := _var11 initialize.
_var19 := _var9 yearsWorkExperience: _var14.
_var20 := _var4 yearsWorkExperience.
_var21 := 45.
_var22 := _var0 yearsWorkExperience: _var10.
_var23 := _var9 nickname.
_var15 := 'teacher_Ann'.
_var24 := _var30 yearsWorkExperience: _var20.
_var25 := _var24 nickname.
_var26 := _var7 yearsWorkExperience: _var10.
_var27 := _var26 yearsWorkExperience: _var10.
_var28 := _var4 yearsWorkExperience: _var21.
self assert: _var25 equals: _var23.
self assert: _var25 equals: _var5.
self deny: _var25 equals: _var15.
self deny: _var2 equals: _var14.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var21.
self assert: _var2 equals: _var17.
self deny: _var2 equals: _var10.
self deny: _var2 equals: _var3.
self assert: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var31.
self assert: _var2 equals: _var20.
self assert: _var14 equals: _var12.
self deny: _var14 equals: _var21.
self deny: _var14 equals: _var17.
self deny: _var14 equals: _var10.
self assert: _var14 equals: _var3.
self deny: _var14 equals: _var8.
self deny: _var14 equals: _var1.
self assert: _var14 equals: _var31.
self deny: _var14 equals: _var20.
self assert: _var23 equals: _var5.
self deny: _var23 equals: _var15.
self deny: _var12 equals: _var21.
self deny: _var12 equals: _var17.
self deny: _var12 equals: _var10.
self assert: _var12 equals: _var3.
self deny: _var12 equals: _var8.
self deny: _var12 equals: _var1.
self assert: _var12 equals: _var31.
self deny: _var12 equals: _var20.
self deny: _var21 equals: _var17.
self assert: _var21 equals: _var10.
self deny: _var21 equals: _var3.
self deny: _var21 equals: _var8.
self deny: _var21 equals: _var1.
self deny: _var21 equals: _var31.
self deny: _var21 equals: _var20.
self deny: _var17 equals: _var10.
self deny: _var17 equals: _var3.
self assert: _var17 equals: _var8.
self assert: _var17 equals: _var1.
self deny: _var17 equals: _var31.
self assert: _var17 equals: _var20.
self deny: _var5 equals: _var15.
self deny: _var10 equals: _var3.
self deny: _var10 equals: _var8.
self deny: _var10 equals: _var1.
self deny: _var10 equals: _var31.
self deny: _var10 equals: _var20.
self deny: _var3 equals: _var8.
self deny: _var3 equals: _var1.
self assert: _var3 equals: _var31.
self deny: _var3 equals: _var20.
self assert: _var8 equals: _var1.
self deny: _var8 equals: _var31.
self assert: _var8 equals: _var20.
self deny: _var1 equals: _var31.
self assert: _var1 equals: _var20.
self deny: _var31 equals: _var20.
self assert: _var25 equals: 'teacher_1'.
self assert: _var2 equals: 0.
self assert: _var14 equals: 100.
self assert: _var23 equals: 'teacher_1'.
self assert: _var12 equals: 100.
self assert: _var21 equals: 45.
self assert: _var17 equals: 0.
self assert: _var5 equals: 'teacher_1'.
self assert: _var10 equals: 45.
self assert: _var3 equals: 100.
self assert: _var15 equals: 'teacher_Ann'.
self assert: _var8 equals: 0.
self assert: _var1 equals: 0.
self assert: _var31 equals: 100.
self assert: _var20 equals: 0
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test4 [
| _var0 _var1 _var2 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 idTeacher.
_var2 := 45.
_var4 := SSTeacher new.
_var5 := _var0 yearsWorkExperience: _var1.
_var6 := SSTeacher new.
_var7 := _var5 initialize.
_var8 := _var6 idTeacher.
_var9 := _var5 yearsWorkExperience: _var2.
_var10 := 45.
_var11 := SSTeacher new.
_var12 := SSTeacher new.
_var13 := SSTeacher new.
_var14 := _var11 idTeacher.
_var15 := _var11 nickname.
_var16 := _var4 yearsWorkExperience.
_var17 := SSTeacher new.
_var18 := SSTeacher new.
_var19 := _var9 yearsWorkExperience: _var14.
_var20 := _var19 yearsWorkExperience.
_var21 := _var4 yearsWorkExperience.
_var22 := _var12 initialize.
_var23 := _var17 initialize.
_var24 := _var5 yearsWorkExperience: _var2.
_var25 := 'teacher_Ann'.
_var26 := _var22 nickname.
_var27 := _var5 idTeacher.
_var28 := 100.
_var29 := _var13 yearsWorkExperience: _var1.
self deny: _var25 equals: _var26.
self deny: _var25 equals: _var15.
self deny: _var2 equals: _var14.
self deny: _var2 equals: _var21.
self deny: _var2 equals: _var28.
self assert: _var2 equals: _var10.
self deny: _var2 equals: _var8.
self deny: _var2 equals: _var1.
self deny: _var2 equals: _var20.
self deny: _var2 equals: _var27.
self deny: _var2 equals: _var16.
self deny: _var14 equals: _var21.
self assert: _var14 equals: _var28.
self deny: _var14 equals: _var10.
self assert: _var14 equals: _var8.
self assert: _var14 equals: _var1.
self assert: _var14 equals: _var20.
self assert: _var14 equals: _var27.
self deny: _var14 equals: _var16.
self deny: _var21 equals: _var28.
self deny: _var21 equals: _var10.
self deny: _var21 equals: _var8.
self deny: _var21 equals: _var1.
self deny: _var21 equals: _var20.
self deny: _var21 equals: _var27.
self assert: _var21 equals: _var16.
self deny: _var28 equals: _var10.
self assert: _var28 equals: _var8.
self assert: _var28 equals: _var1.
self assert: _var28 equals: _var20.
self assert: _var28 equals: _var27.
self deny: _var28 equals: _var16.
self deny: _var10 equals: _var8.
self deny: _var10 equals: _var1.
self deny: _var10 equals: _var20.
self deny: _var10 equals: _var27.
self deny: _var10 equals: _var16.
self assert: _var26 equals: _var15.
self assert: _var8 equals: _var1.
self assert: _var8 equals: _var20.
self assert: _var8 equals: _var27.
self deny: _var8 equals: _var16.
self assert: _var1 equals: _var20.
self assert: _var1 equals: _var27.
self deny: _var1 equals: _var16.
self assert: _var20 equals: _var27.
self deny: _var20 equals: _var16.
self deny: _var27 equals: _var16.
self assert: _var25 equals: 'teacher_Ann'.
self assert: _var2 equals: 45.
self assert: _var14 equals: 100.
self assert: _var21 equals: 0.
self assert: _var28 equals: 100.
self assert: _var10 equals: 45.
self assert: _var26 equals: 'teacher_1'.
self assert: _var15 equals: 'teacher_1'.
self assert: _var8 equals: 100.
self assert: _var1 equals: 100.
self assert: _var20 equals: 100.
self assert: _var27 equals: 100.
self assert: _var16 equals: 0
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test5 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var30 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var32 _var21 _var22 _var23 _var24 _var31 _var25 _var26 _var28 _var29 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := 45.
_var3 := _var0 yearsWorkExperience.
_var4 := _var0 nickname.
_var5 := 45.
_var6 := SSTeacher new.
_var7 := _var6 initialize.
_var30 := _var0 yearsWorkExperience.
_var8 := _var6 idTeacher.
_var9 := _var0 yearsWorkExperience: _var3.
_var10 := 100.
_var11 := SSTeacher new.
_var12 := 100.
_var13 := _var9 yearsWorkExperience: _var1.
_var14 := _var6 nickname.
_var15 := _var13 initialize.
_var16 := _var11 initialize.
_var17 := 100.
_var18 := _var7 nickname.
_var19 := SSTeacher new.
_var20 := 100.
_var32 := SSTeacher new.
_var21 := _var9 yearsWorkExperience.
_var22 := _var11 yearsWorkExperience: _var3.
_var23 := _var7 nickname.
_var24 := _var16 initialize.
_var31 := _var0 yearsWorkExperience.
_var25 := _var19 yearsWorkExperience: _var5.
_var26 := 'teacher_Ann'.
_var28 := _var11 idTeacher.
_var29 := 100.
self assert: _var4 equals: _var14.
self assert: _var4 equals: _var23.
self deny: _var4 equals: _var26.
self assert: _var4 equals: _var18.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var30.
self deny: _var2 equals: _var21.
self deny: _var2 equals: _var28.
self deny: _var2 equals: _var17.
self assert: _var2 equals: _var5.
self deny: _var2 equals: _var10.
self deny: _var2 equals: _var3.
self deny: _var2 equals: _var8.
self deny: _var2 equals: _var1.
self deny: _var2 equals: _var31.
self deny: _var2 equals: _var29.
self deny: _var2 equals: _var20.
self assert: _var14 equals: _var23.
self deny: _var14 equals: _var26.
self assert: _var14 equals: _var18.
self deny: _var23 equals: _var26.
self assert: _var23 equals: _var18.
self deny: _var12 equals: _var30.
self deny: _var12 equals: _var21.
self assert: _var12 equals: _var28.
self assert: _var12 equals: _var17.
self deny: _var12 equals: _var5.
self assert: _var12 equals: _var10.
self deny: _var12 equals: _var3.
self assert: _var12 equals: _var8.
self deny: _var12 equals: _var1.
self deny: _var12 equals: _var31.
self assert: _var12 equals: _var29.
self assert: _var12 equals: _var20.
self assert: _var30 equals: _var21.
self deny: _var30 equals: _var28.
self deny: _var30 equals: _var17.
self deny: _var30 equals: _var5.
self deny: _var30 equals: _var10.
self assert: _var30 equals: _var3.
self deny: _var30 equals: _var8.
self assert: _var30 equals: _var1.
self assert: _var30 equals: _var31.
self deny: _var30 equals: _var29.
self deny: _var30 equals: _var20.
self deny: _var21 equals: _var28.
self deny: _var21 equals: _var17.
self deny: _var21 equals: _var5.
self deny: _var21 equals: _var10.
self assert: _var21 equals: _var3.
self deny: _var21 equals: _var8.
self assert: _var21 equals: _var1.
self assert: _var21 equals: _var31.
self deny: _var21 equals: _var29.
self deny: _var21 equals: _var20.
self assert: _var28 equals: _var17.
self deny: _var28 equals: _var5.
self assert: _var28 equals: _var10.
self deny: _var28 equals: _var3.
self assert: _var28 equals: _var8.
self deny: _var28 equals: _var1.
self deny: _var28 equals: _var31.
self assert: _var28 equals: _var29.
self assert: _var28 equals: _var20.
self deny: _var17 equals: _var5.
self assert: _var17 equals: _var10.
self deny: _var17 equals: _var3.
self assert: _var17 equals: _var8.
self deny: _var17 equals: _var1.
self deny: _var17 equals: _var31.
self assert: _var17 equals: _var29.
self assert: _var17 equals: _var20.
self deny: _var5 equals: _var10.
self deny: _var5 equals: _var3.
self deny: _var5 equals: _var8.
self deny: _var5 equals: _var1.
self deny: _var5 equals: _var31.
self deny: _var5 equals: _var29.
self deny: _var5 equals: _var20.
self deny: _var10 equals: _var3.
self assert: _var10 equals: _var8.
self deny: _var10 equals: _var1.
self deny: _var10 equals: _var31.
self assert: _var10 equals: _var29.
self assert: _var10 equals: _var20.
self deny: _var26 equals: _var18.
self deny: _var3 equals: _var8.
self assert: _var3 equals: _var1.
self assert: _var3 equals: _var31.
self deny: _var3 equals: _var29.
self deny: _var3 equals: _var20.
self deny: _var8 equals: _var1.
self deny: _var8 equals: _var31.
self assert: _var8 equals: _var29.
self assert: _var8 equals: _var20.
self assert: _var1 equals: _var31.
self deny: _var1 equals: _var29.
self deny: _var1 equals: _var20.
self deny: _var31 equals: _var29.
self deny: _var31 equals: _var20.
self assert: _var29 equals: _var20.
self assert: _var4 equals: 'teacher_1'.
self assert: _var2 equals: 45.
self assert: _var14 equals: 'teacher_1'.
self assert: _var23 equals: 'teacher_1'.
self assert: _var12 equals: 100.
self assert: _var30 equals: 0.
self assert: _var21 equals: 0.
self assert: _var28 equals: 100.
self assert: _var17 equals: 100.
self assert: _var5 equals: 45.
self assert: _var10 equals: 100.
self assert: _var26 equals: 'teacher_Ann'.
self assert: _var3 equals: 0.
self assert: _var8 equals: 100.
self assert: _var1 equals: 0.
self assert: _var31 equals: 0.
self assert: _var29 equals: 100.
self assert: _var18 equals: 'teacher_1'.
self assert: _var20 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test6 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var0 idTeacher.
_var4 := SSTeacher new.
_var5 := _var4 nickname.
_var7 := _var4 initialize.
_var8 := SSTeacher new.
_var9 := 'teacher_Ann'.
_var10 := _var8 idTeacher.
_var11 := SSTeacher new.
_var12 := SSTeacher new.
_var13 := _var12 idTeacher.
_var14 := _var0 nickname.
_var15 := _var7 yearsWorkExperience.
_var16 := SSTeacher new.
_var17 := SSTeacher new.
_var18 := _var4 yearsWorkExperience: _var1.
_var19 := _var18 yearsWorkExperience.
_var20 := _var12 yearsWorkExperience.
_var21 := _var0 initialize.
_var22 := _var8 initialize.
_var23 := _var18 yearsWorkExperience: _var20.
_var24 := '''qteacher_AnJ'''.
_var25 := _var21 nickname.
_var26 := _var22 idTeacher.
_var27 := 100.
_var28 := _var21 yearsWorkExperience: _var2.
self deny: _var25 equals: _var9.
self assert: _var25 equals: _var14.
self assert: _var25 equals: _var5.
self deny: _var25 equals: _var24.
self deny: _var9 equals: _var14.
self deny: _var9 equals: _var5.
self deny: _var9 equals: _var24.
self assert: _var2 equals: _var19.
self deny: _var2 equals: _var10.
self deny: _var2 equals: _var26.
self assert: _var2 equals: _var15.
self deny: _var2 equals: _var3.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var13.
self assert: _var2 equals: _var20.
self deny: _var2 equals: _var27.
self assert: _var14 equals: _var5.
self deny: _var14 equals: _var24.
self deny: _var19 equals: _var10.
self deny: _var19 equals: _var26.
self assert: _var19 equals: _var15.
self deny: _var19 equals: _var3.
self assert: _var19 equals: _var1.
self deny: _var19 equals: _var13.
self assert: _var19 equals: _var20.
self deny: _var19 equals: _var27.
self deny: _var5 equals: _var24.
self assert: _var10 equals: _var26.
self deny: _var10 equals: _var15.
self assert: _var10 equals: _var3.
self deny: _var10 equals: _var1.
self assert: _var10 equals: _var13.
self deny: _var10 equals: _var20.
self assert: _var10 equals: _var27.
self deny: _var26 equals: _var15.
self assert: _var26 equals: _var3.
self deny: _var26 equals: _var1.
self assert: _var26 equals: _var13.
self deny: _var26 equals: _var20.
self assert: _var26 equals: _var27.
self deny: _var15 equals: _var3.
self assert: _var15 equals: _var1.
self deny: _var15 equals: _var13.
self assert: _var15 equals: _var20.
self deny: _var15 equals: _var27.
self deny: _var3 equals: _var1.
self assert: _var3 equals: _var13.
self deny: _var3 equals: _var20.
self assert: _var3 equals: _var27.
self deny: _var1 equals: _var13.
self assert: _var1 equals: _var20.
self deny: _var1 equals: _var27.
self deny: _var13 equals: _var20.
self assert: _var13 equals: _var27.
self deny: _var20 equals: _var27.
self assert: _var25 equals: 'teacher_1'.
self assert: _var9 equals: 'teacher_Ann'.
self assert: _var2 equals: 0.
self assert: _var14 equals: 'teacher_1'.
self assert: _var19 equals: 0.
self assert: _var5 equals: 'teacher_1'.
self assert: _var10 equals: 100.
self assert: _var26 equals: 100.
self assert: _var15 equals: 0.
self assert: _var3 equals: 100.
self assert: _var24 equals: '''qteacher_AnJ'''.
self assert: _var1 equals: 0.
self assert: _var13 equals: 100.
self assert: _var20 equals: 0.
self assert: _var27 equals: 100
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test7 [
| _var0 _var29 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var30 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var31 _var28 |
_var0 := SSTeacher new.
_var29 := SSTeacher new.
_var1 := _var29 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := _var29 nickname.
_var4 := 45.
_var5 := 'teacher_Ann'.
_var6 := SSTeacher new.
_var7 := _var6 initialize.
_var8 := _var29 idTeacher.
_var9 := _var29 idTeacher.
_var10 := _var7 idTeacher.
_var11 := _var29 yearsWorkExperience: _var10.
_var12 := _var29 nickname.
_var13 := _var11 yearsWorkExperience.
_var30 := _var0 yearsWorkExperience.
_var14 := SSTeacher new.
_var15 := SSTeacher new.
_var16 := _var11 yearsWorkExperience: _var8.
_var17 := _var15 yearsWorkExperience.
_var18 := 45.
_var19 := 100.
_var20 := _var29 yearsWorkExperience.
_var21 := _var16 initialize.
_var22 := _var14 initialize.
_var23 := SSTeacher new.
_var24 := _var11 initialize.
_var25 := _var14 yearsWorkExperience: _var19.
_var26 := SSTeacher new.
_var27 := _var22 nickname.
_var31 := _var14 yearsWorkExperience: _var19.
_var28 := SSTeacher new.
self deny: _var4 equals: _var9.
self deny: _var4 equals: _var2.
self deny: _var4 equals: _var30.
self deny: _var4 equals: _var19.
self deny: _var4 equals: _var10.
self deny: _var4 equals: _var17.
self deny: _var4 equals: _var8.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var13.
self assert: _var4 equals: _var18.
self deny: _var4 equals: _var20.
self deny: _var9 equals: _var2.
self deny: _var9 equals: _var30.
self assert: _var9 equals: _var19.
self assert: _var9 equals: _var10.
self deny: _var9 equals: _var17.
self assert: _var9 equals: _var8.
self deny: _var9 equals: _var1.
self assert: _var9 equals: _var13.
self deny: _var9 equals: _var18.
self assert: _var9 equals: _var20.
self assert: _var2 equals: _var30.
self deny: _var2 equals: _var19.
self deny: _var2 equals: _var10.
self assert: _var2 equals: _var17.
self deny: _var2 equals: _var8.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var13.
self deny: _var2 equals: _var18.
self deny: _var2 equals: _var20.
self deny: _var12 equals: _var5.
self assert: _var12 equals: _var3.
self assert: _var12 equals: _var27.
self deny: _var30 equals: _var19.
self deny: _var30 equals: _var10.
self assert: _var30 equals: _var17.
self deny: _var30 equals: _var8.
self assert: _var30 equals: _var1.
self deny: _var30 equals: _var13.
self deny: _var30 equals: _var18.
self deny: _var30 equals: _var20.
self assert: _var19 equals: _var10.
self deny: _var19 equals: _var17.
self assert: _var19 equals: _var8.
self deny: _var19 equals: _var1.
self assert: _var19 equals: _var13.
self deny: _var19 equals: _var18.
self assert: _var19 equals: _var20.
self deny: _var5 equals: _var3.
self deny: _var5 equals: _var27.
self deny: _var10 equals: _var17.
self assert: _var10 equals: _var8.
self deny: _var10 equals: _var1.
self assert: _var10 equals: _var13.
self deny: _var10 equals: _var18.
self assert: _var10 equals: _var20.
self deny: _var17 equals: _var8.
self assert: _var17 equals: _var1.
self deny: _var17 equals: _var13.
self deny: _var17 equals: _var18.
self deny: _var17 equals: _var20.
self assert: _var3 equals: _var27.
self deny: _var8 equals: _var1.
self assert: _var8 equals: _var13.
self deny: _var8 equals: _var18.
self assert: _var8 equals: _var20.
self deny: _var1 equals: _var13.
self deny: _var1 equals: _var18.
self deny: _var1 equals: _var20.
self deny: _var13 equals: _var18.
self assert: _var13 equals: _var20.
self deny: _var18 equals: _var20.
self assert: _var4 equals: 45.
self assert: _var9 equals: 100.
self assert: _var2 equals: 0.
self assert: _var12 equals: 'teacher_1'.
self assert: _var30 equals: 0.
self assert: _var19 equals: 100.
self assert: _var5 equals: 'teacher_Ann'.
self assert: _var10 equals: 100.
self assert: _var17 equals: 0.
self assert: _var3 equals: 'teacher_1'.
self assert: _var8 equals: 100.
self assert: _var1 equals: 0.
self assert: _var13 equals: 100.
self assert: _var18 equals: 45.
self assert: _var20 equals: 100.
self assert: _var27 equals: 'teacher_1'
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test8 [
| _var1 _var30 _var31 _var0 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var32 _var22 _var23 _var24 _var25 _var26 _var27 |
_var1 := 141.
_var30 := SSTeacher new.
_var31 := _var30 initialize.
_var0 := _var30 yearsWorkExperience.
_var2 := _var31 idTeacher.
_var3 := SSTeacher new.
_var4 := _var3 yearsWorkExperience.
_var5 := _var3 nickname.
_var6 := _var31 initialize.
_var7 := _var31 idTeacher.
_var8 := 'teacher_Ann'.
_var9 := _var6 idTeacher.
_var10 := SSTeacher new.
_var11 := _var6 idTeacher.
_var12 := _var30 yearsWorkExperience: _var4.
_var13 := _var6 nickname.
_var14 := _var31 yearsWorkExperience.
_var15 := SSTeacher new.
_var16 := SSTeacher new.
_var17 := _var6 yearsWorkExperience: _var14.
_var18 := _var10 yearsWorkExperience.
_var19 := 45.
_var20 := _var15 yearsWorkExperience.
_var21 := _var15 initialize.
_var32 := _var3 yearsWorkExperience.
_var22 := _var30 initialize.
_var23 := 100.
_var24 := SSTeacher new.
_var25 := SSTeacher new.
_var26 := _var16 nickname.
_var27 := SSTeacher new.
self deny: _var4 equals: _var9.
self deny: _var4 equals: _var2.
self assert: _var4 equals: _var14.
self assert: _var4 equals: _var32.
self deny: _var4 equals: _var23.
self deny: _var4 equals: _var7.
self assert: _var4 equals: _var0.
self deny: _var4 equals: _var19.
self deny: _var4 equals: _var1.
self deny: _var4 equals: _var11.
self assert: _var4 equals: _var18.
self assert: _var4 equals: _var20.
self assert: _var9 equals: _var2.
self deny: _var9 equals: _var14.
self deny: _var9 equals: _var32.
self assert: _var9 equals: _var23.
self assert: _var9 equals: _var7.
self deny: _var9 equals: _var0.
self deny: _var9 equals: _var19.
self deny: _var9 equals: _var1.
self assert: _var9 equals: _var11.
self deny: _var9 equals: _var18.
self deny: _var9 equals: _var20.
self deny: _var2 equals: _var14.
self deny: _var2 equals: _var32.
self assert: _var2 equals: _var23.
self assert: _var2 equals: _var7.
self deny: _var2 equals: _var0.
self deny: _var2 equals: _var19.
self deny: _var2 equals: _var1.
self assert: _var2 equals: _var11.
self deny: _var2 equals: _var18.
self deny: _var2 equals: _var20.
self assert: _var14 equals: _var32.
self deny: _var14 equals: _var23.
self deny: _var14 equals: _var7.
self assert: _var14 equals: _var0.
self deny: _var14 equals: _var19.
self deny: _var14 equals: _var1.
self deny: _var14 equals: _var11.
self assert: _var14 equals: _var18.
self assert: _var14 equals: _var20.
self deny: _var32 equals: _var23.
self deny: _var32 equals: _var7.
self assert: _var32 equals: _var0.
self deny: _var32 equals: _var19.
self deny: _var32 equals: _var1.
self deny: _var32 equals: _var11.
self assert: _var32 equals: _var18.
self assert: _var32 equals: _var20.
self assert: _var23 equals: _var7.
self deny: _var23 equals: _var0.
self deny: _var23 equals: _var19.
self deny: _var23 equals: _var1.
self assert: _var23 equals: _var11.
self deny: _var23 equals: _var18.
self deny: _var23 equals: _var20.
self deny: _var7 equals: _var0.
self deny: _var7 equals: _var19.
self deny: _var7 equals: _var1.
self assert: _var7 equals: _var11.
self deny: _var7 equals: _var18.
self deny: _var7 equals: _var20.
self deny: _var0 equals: _var19.
self deny: _var0 equals: _var1.
self deny: _var0 equals: _var11.
self assert: _var0 equals: _var18.
self assert: _var0 equals: _var20.
self deny: _var19 equals: _var1.
self deny: _var19 equals: _var11.
self deny: _var19 equals: _var18.
self deny: _var19 equals: _var20.
self assert: _var5 equals: _var26.
self deny: _var5 equals: _var8.
self assert: _var5 equals: _var13.
self deny: _var26 equals: _var8.
self assert: _var26 equals: _var13.
self deny: _var8 equals: _var13.
self deny: _var1 equals: _var11.
self deny: _var1 equals: _var18.
self deny: _var1 equals: _var20.
self deny: _var11 equals: _var18.
self deny: _var11 equals: _var20.
self assert: _var18 equals: _var20.
self assert: _var4 equals: 0.
self assert: _var9 equals: 100.
self assert: _var2 equals: 100.
self assert: _var14 equals: 0.
self assert: _var32 equals: 0.
self assert: _var23 equals: 100.
self assert: _var7 equals: 100.
self assert: _var0 equals: 0.
self assert: _var19 equals: 45.
self assert: _var5 equals: 'teacher_1'.
self assert: _var26 equals: 'teacher_1'.
self assert: _var8 equals: 'teacher_Ann'.
self assert: _var1 equals: 141.
self assert: _var13 equals: 'teacher_1'.
self assert: _var11 equals: 100.
self assert: _var18 equals: 0.
self assert: _var20 equals: 0
]

{ #category : #'as yet unclassified' }
SGeneratedTestCase >> test9 [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 _var31 _var32 _var33 |
_var0 := SSTeacher new.
_var1 := _var0 yearsWorkExperience.
_var2 := _var0 yearsWorkExperience.
_var3 := SSTeacher new.
_var4 := SSTeacher new.
_var5 := _var4 yearsWorkExperience: _var1.
_var6 := 'teacher_Ann'.
_var7 := SSTeacher new.
_var8 := _var7 initialize.
_var9 := _var5 idTeacher.
_var10 := SSTeacher new.
_var11 := SSTeacher new.
_var12 := _var4 idTeacher.
_var13 := _var4 yearsWorkExperience: _var9.
_var14 := _var13 idTeacher.
_var15 := _var13 yearsWorkExperience: _var2.
_var16 := _var15 initialize.
_var17 := SSTeacher new.
_var18 := 45.
_var19 := SSTeacher new.
_var20 := _var4 nickname.
_var21 := SSTeacher new.
_var22 := 'teacher_Ann'.
_var23 := _var8 yearsWorkExperience.
_var24 := _var3 idTeacher.
_var25 := _var16 nickname.
_var26 := _var16 initialize.
_var27 := _var5 initialize.
_var28 := 'teacher_Ann'.
_var29 := 'teacher_Ann'.
_var30 := _var7 idTeacher.
_var31 := SSTeacher new.
_var32 := _var3 nickname.
_var33 := _var31 idTeacher.
self assert: _var25 equals: _var32.
self deny: _var25 equals: _var28.
self deny: _var25 equals: _var22.
self deny: _var25 equals: _var29.
self deny: _var25 equals: _var6.
self assert: _var25 equals: _var20.
self deny: _var9 equals: _var2.
self assert: _var9 equals: _var14.
self deny: _var9 equals: _var23.
self assert: _var9 equals: _var12.
self assert: _var9 equals: _var30.
self assert: _var9 equals: _var24.
self assert: _var9 equals: _var33.
self deny: _var9 equals: _var1.
self deny: _var9 equals: _var18.
self deny: _var2 equals: _var14.
self assert: _var2 equals: _var23.
self deny: _var2 equals: _var12.
self deny: _var2 equals: _var30.
self deny: _var2 equals: _var24.
self deny: _var2 equals: _var33.
self assert: _var2 equals: _var1.
self deny: _var2 equals: _var18.
self deny: _var14 equals: _var23.
self assert: _var14 equals: _var12.
self assert: _var14 equals: _var30.
self assert: _var14 equals: _var24.
self assert: _var14 equals: _var33.
self deny: _var14 equals: _var1.
self deny: _var14 equals: _var18.
self deny: _var23 equals: _var12.
self deny: _var23 equals: _var30.
self deny: _var23 equals: _var24.
self deny: _var23 equals: _var33.
self assert: _var23 equals: _var1.
self deny: _var23 equals: _var18.
self deny: _var32 equals: _var28.
self deny: _var32 equals: _var22.
self deny: _var32 equals: _var29.
self deny: _var32 equals: _var6.
self assert: _var32 equals: _var20.
self assert: _var12 equals: _var30.
self assert: _var12 equals: _var24.
self assert: _var12 equals: _var33.
self deny: _var12 equals: _var1.
self deny: _var12 equals: _var18.
self assert: _var28 equals: _var22.
self assert: _var28 equals: _var29.
self assert: _var28 equals: _var6.
self deny: _var28 equals: _var20.
self assert: _var30 equals: _var24.
self assert: _var30 equals: _var33.
self deny: _var30 equals: _var1.
self deny: _var30 equals: _var18.
self assert: _var24 equals: _var33.
self deny: _var24 equals: _var1.
self deny: _var24 equals: _var18.
self deny: _var33 equals: _var1.
self deny: _var33 equals: _var18.
self deny: _var1 equals: _var18.
self assert: _var22 equals: _var29.
self assert: _var22 equals: _var6.
self deny: _var22 equals: _var20.
self assert: _var29 equals: _var6.
self deny: _var29 equals: _var20.
self deny: _var6 equals: _var20.
self assert: _var25 equals: 'teacher_1'.
self assert: _var9 equals: 100.
self assert: _var2 equals: 0.
self assert: _var14 equals: 100.
self assert: _var23 equals: 0.
self assert: _var32 equals: 'teacher_1'.
self assert: _var12 equals: 100.
self assert: _var28 equals: 'teacher_Ann'.
self assert: _var30 equals: 100.
self assert: _var24 equals: 100.
self assert: _var33 equals: 100.
self assert: _var1 equals: 0.
self assert: _var22 equals: 'teacher_Ann'.
self assert: _var29 equals: 'teacher_Ann'.
self assert: _var18 equals: 45.
self assert: _var6 equals: 'teacher_Ann'.
self assert: _var20 equals: 'teacher_1'
]
