
language: smalltalk
sudo: false

os:
- linux

smalltalk:
  - Pharo64-8.0
  - Pharo64-7.0
  - Pharo64-6.1
  
matrix:
  fast_finish: true
  allow_failures:
    - smalltalk:
      - Pharo64-7.0
      - Pharo64-6.1
