Class {
	#name : #STestCaseCompiler,
	#superclass : #Object,
	#category : #SmallSuiteCompiler
}

{ #category : #'as yet unclassified' }
STestCaseCompiler >> testCaseCompiled [
| _var10 _var0 _var1 _var2 _var3 _var4 _var19 _var5 _var6 _var7 _var8 _var9 _var11 _var12 _var13 _var14 _var15 _var20 _var16 _var18 _var17 |
_var10 := 'Customer Relationship'.
_var0 := RTAMItem new.
_var1 := 'Customer Relationship'.
_var2 := 'Bonus Card'.
_var3 := 'Bonus Card'.
_var4 := 'Customer Relationship'.
_var19 := 'Bonus Card'.
_var5 := _var0 row: _var2.
_var6 := 'Bonus Card'.
_var7 := RTAMItem new.
_var8 := _var0
	color:
		(Color
			r: 0.8
			g: 1.0
			b: 0.6
			alpha: 1.0).
_var9 := RTAMItem new.
_var11 := _var0 row: _var10.
_var12 := RTAMItem new.
_var13 := _var0 itemName: _var1.
_var14 := _var0 itemName: _var3.
_var15 := _var0 column: _var3.
_var20 := _var0 itemName: _var19.
_var16 := _var0
	color:
		(Color
			r: 0.8
			g: 1.0
			b: 0.6
			alpha: 1.0).
_var18 := _var0
	color:
		(Color
			r: 0.8
			g: 1.0
			b: 0.6
			alpha: 1.0).
_var17 := '{Bonus CarV'
]
