Class {
	#name : #STestCaseCompiler,
	#superclass : #Object,
	#category : #SmallSuiteCompiler
}

{ #category : #'as yet unclassified' }
STestCaseCompiler >> testCaseCompiled [
| _var14 _var1 _var0 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 |
_var14 := 8.
_var1 := SStack newStackWith: #(2 4 6 1).
_var0 := _var1 pop.
_var2 := _var1 pop.
_var3 := _var1 top.
_var4 := _var1 pop.
_var5 := _var1 pop.
_var6 := _var1 pop.
_var7 := _var1 top.
_var8 := _var1 top.
_var9 := _var1 pop.
_var10 := _var1 pop
]
