Class {
	#name : #STestCaseCompiler,
	#superclass : #Object,
	#category : #SmallSuiteCompiler
}

{ #category : #'as yet unclassified' }
STestCaseCompiler >> testCaseCompiled [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 |
_var0 := RTInteractiveComposerExample new.
_var1 := RTBounds new.
_var2 := RTInteractiveTreeBuilder new.
_var3 := RTVerticalDraggableView new.
_var4 := RTCPPAnalysisPlugin new.
_var5 := RTScatterplotMap new.
_var6 := RTApplicationMatrix new.
_var7 := RTSunburstConstantWidthLayout new.
_var8 := RTExploraNodeLazy new.
_var9 := RTBucketColor new.
_var10 := RTRadar new.
_var11 := RTSubTimelineSet new.
_var12 := RTFixedPopup new.
_var13 := RTApplicationMatrix new.
_var14 := RTDevVarDecorator new.
_var15 := RTAbstractSunburstLayout new.
_var16 := RTContinuousPopup new.
_var17 := RTIcon new.
_var18 := RTNameCloudDictionary new.
_var19 := RTColorPalette new.
_var20 := RTNumberAnimation new.
_var21 := RTPieBuilder new.
_var22 := RTDraggable new.
_var23 := RTVerticalAllValuesDecorator new
]
