Class {
	#name : #SCompilerTestCase,
	#superclass : #Object,
	#category : #'SmallSuiteGenerator-Core'
}

{ #category : #'as yet unclassified' }
SCompilerTestCase >> compileTestCase [
| _var0 _var1 _var2 _var3 _var4 _var5 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 _var31 _var32 _var33 |
_var0 := 0.
_var1 := SSTeacher new.
_var2 := _var1 yearsWorkExperience.
_var3 := _var1 initialize.
_var4 := _var1 idTeacher.
_var5 := _var1 idTeacher.
_var6 := 'teacher_Ann'.
_var7 := _var1 yearsWorkExperience.
_var8 := _var1 idTeacher.
_var9 := SSTeacher new.
_var10 := _var1 nickname.
_var11 := 0.
_var12 := 100.
_var13 := 100.
_var14 := SSTeacher new.
_var15 := SSTeacher new.
_var16 := SSTeacher new.
_var17 := _var1 initialize.
_var18 := _var1 nickname.
_var19 := SSTeacher new.
_var20 := SSTeacher new.
_var21 := SSTeacher new.
_var22 := _var1 yearsWorkExperience.
_var23 := _var1 yearsWorkExperience.
_var24 := _var1 yearsWorkExperience.
_var25 := _var1 yearsWorkExperience.
_var26 := 'teacher_Ann'.
_var27 := _var1 nickname.
_var28 := _var1 initialize.
_var29 := _var1 yearsWorkExperience.
_var30 := _var1 initialize.
_var31 := _var1 initialize.
_var32 := _var1 initialize.
_var33 := _var1 initialize
]
