Class {
	#name : #SConfigurationVisualWorks,
	#superclass : #SConfiguration,
	#category : #'SmallSuiteGenerator-Core'
}

{ #category : #accessing }
SConfigurationVisualWorks class >> classTestCaseFactory [
	^ STestCaseFactoryVisualWorks 
]

{ #category : #logging }
SConfigurationVisualWorks class >> cleanAllLogs [ 
	
]

{ #category : #logging }
SConfigurationVisualWorks class >> clearLog [ 
	
]

{ #category : #'instance creation' }
SConfigurationVisualWorks class >> fileLogger: fileName [
]

{ #category : #logging }
SConfigurationVisualWorks class >> saveOnLog: string [
]
