Class {
	#name : #SSCustomMethods,
	#superclass : #SSAbstractSettingMethods,
	#category : #'SmallSuiteGenerator-Strategies'
}

{ #category : #'as yet unclassified' }
SSCustomMethods class >> setUp [
    ^ self
]

{ #category : #'as yet unclassified' }
SSCustomMethods class >> tearDown [
    ^ self
]

{ #category : #'as yet unclassified' }
SSCustomMethods >> setUp [
    ^ self
]

{ #category : #'as yet unclassified' }
SSCustomMethods >> tearDown [
    ^ self
]
