Extension { #name : #SSTestRunner }

{ #category : #'*SmallSuiteGenerator-Exception-Management' }
SSTestRunner >> performTest [
	| _var0 _var2 _var3 _var4 _var5 _var1 _var6 _var7 _var8 _var9 _var10 _var11 _var12 _var13 _var14 _var15 _var16 _var17 _var18 _var19 _var20 _var21 _var22 _var23 _var24 _var25 _var26 _var27 _var28 _var29 _var30 _var31 _var32 |
	_var0 := RTView new.
	_var2 := RTView new.
	_var3 := RTView new.
	_var4 := RTView new.
	_var5 := RTView new.
	_var1 := RTView new.
	_var6 := RTView new.
	_var7 := RTView new.
	_var8 := RTView new.
	_var9 := RTView new.
	_var10 := RTView new.
	_var11 := _var0 initialize.
	_var12 := RTView new.
	_var13 := RTView new.
	_var14 := _var0 initialize.
	_var15 := RTView new.
	_var16 := _var0 initialize.
	_var17 := RTView new.
	_var18 := RTView new.
	_var19 := _var0 initialize.
	_var20 := RTView new.
	_var21 := RTView new.
	_var22 := RTView new.
	_var23 := _var0 initializeContent.
	_var24 := RTView new.
	_var25 := RTView new.
	_var26 := RTView new.
	_var27 := RTView new.
	_var28 := RTView new.
	_var29 := RTView new.
	_var30 := RTView new.
	_var31 := RTView new.
	_var32 := _var0 initialize.
	^ self analyze: thisContext
]
